### ISSUE TITLE
allow tags to be shown on front-page like contexts

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1050]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/1050_

Either I would like to be able to assign multiple contexts to an action, or be able to show lists of actions having "visible on front page" tags (just like is currently done for contexts).

The main thing I'm trying to get is a list of actions belonging to a tag (or context) on the front page, where a single action can appear under more than one context/tag.

As an example (on the front page):
[tag1]
action1
action2

[tag2]
action5
action2
action7

...

_Originally reported by edgimar on July 7, 2010 at 13:05:54 (+0100) against version git-devel_

**Comment by mattr-** [comment]
Closing in favor of #1193
