### ISSUE TITLE
allow adding of "visual-notes" via javascript SVG editor

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1057]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/1057_

There's a nice javascript SVG editor available at http://code.google.com/p/svg-edit/, which I think would be very cool if it were integrated with tracks, so that instead of just adding "notes" to a project / etc., you could add a "visual note" which just fires up the svg-editor instead of opening a textbox.  See the editor demo at http://svg-edit.googlecode.com/svn/branches/2.5/editor/svg-editor.html -- it's quite nice.

_Originally reported by edgimar on August 8, 2010 at 08:30:30 (+0000) against version git-devel_

**Comment by mattr-** [comment]
Going to close in favor of generic attachments and rendering them inline (which is captured in another issue)
