### ISSUE TITLE
need assert statements in the code

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1233]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/1233_

Tracks needs assert statements in the code to check preconditions and postconditions for functions. They help uncover errors that have a long delay until they cause a failure, and they would also be the first step towards automated testing of the code.

I assume that this will need some discussion.

_Originally reported by popsch on December 12, 2011 at 08:41:02 (-0700)_

**Comment by C-Otto** [comment]
I think this can be closed.

**Comment by ZeiP** [comment]
This is a rather large change and we already have tests, so closing this. Open a new issue if necessary.
