### ISSUE TITLE
Invalid Dependencies

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1401]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/1401_

Dependent objects are supposed to impose a partial ordering between Todos. However this can be broken as there are no sufficient checks in TodosController#add_predecessor. Therefore it's possible to have a Todo have itself as a predecessor, for multiple Dependencies to form a cycle, or to have multiple dependencies between the same two Todos.

The interface disallows this but it is still possible to invalidate the database by sending custom http post requests or via some exposed API. This defect has minor severity but should be reported.

_Originally reported by Bocete on February 2, 2013 at 22:03:04 (+0000) against version git-devel_

**Comment by C-Otto** [comment]
I suggest ro (also) reopen this bug report. The validation code is there, but it is not triggered before introducing the wrong dependency. #1754 describes the same bug.
