### ISSUE TITLE
True Multi-User Capability

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1514]
_Migrated from the original issue #47 at https://www.assembla.com/spaces/tracks-tickets/tickets/47_

I've integrated true multi-user functionality using sessions and some database mods into a previous version of Tracks.  I will be submitting a patch after making appropriate modifications to the current trunk.

_Originally reported by Anonymous on April 4, 2005 at 08:49:43 (+0200)_

**Comment by ZeiP** [comment]
Added the delegate part to #527 as a comment. The multi-user functionality already exists and a sign-up link wasn't explicitly suggested, so closing the issue.
