### ISSUE TITLE
provide some information on GTD concepts?

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1678]
_Migrated from the original issue #211 at https://www.assembla.com/spaces/tracks-tickets/tickets/211_

Hello,

I got to this project because of my recent interests in rails. However, I don't know anything about GDT (and have been looking for some more information about this).

Maybe you could provide some more information on the GDT concepts (or a small 'tutorial' on how to use Tracks) on the wiki?

_Originally reported by Anonymous on February 2, 2006 at 05:21:16 (-0800)_

**Comment by stderr-enst** [comment]
ZeiP just pointed me to this issue.
For me https://gtdfh.branchable.com/ was the most useful resource to get started with Tracks and GTD. Afterwards I also bought the Book and iterated on how I do things with Tracks.
If I can find the time I can try to write something up, but I can't promise anything at this point. :)

**Comment by ZeiP** [comment]
Awesome, thanks! It'd be great if you (and others who are using Tracks for a true GTD process) could open up your Tracks processes so we could write some documentation on it – I have to admit I still don't have an actual GTD process going, for me Tracks is currently more like a task list.

**Comment by stderr-enst** [comment]
It is already May, but here is a first dump of my thoughts on what GTD is and how to use it with Tracks:

https://github.com/TracksApp/tracks/wiki/GTD-on-Tracks

Others are welcome to iterate on this as well!
If you think anything is not covered or should be presented differently, let me know!

**Comment by ZeiP** [comment]
@stderr-enst, awesome, thanks! I re-organised our documentation a bit to make it easier to find: https://github.com/TracksApp/tracks/wiki/User-manual-and-help . I'll also check some kind of link to the Tracks software itself for the next version.

I think this is a very good basic manual. However, if anyone knows / can figure out some instructions on how to use the tickler, that'd be great – it's something I haven't yet figured out a use for.

**Comment by stderr-enst** [comment]
> However, if anyone knows / can figure out some instructions on how to use the tickler, that'd be great – it's something I haven't yet figured out a use for.

Huh, that makes me curious. I have always thought that the tickler is just a list of all actions that are not shown today.
So if you set a "show by" date it goes to the tickler. Is there more to it?

I use `show by` extensively and it is one of the main features why tracks worked so well for me over the last 5 years.
I go through all the actions that are presented to me today and defer everything that I don't want to deal with today. This way I end up with a manageable list that doesn't feel overwhelming, while still having everything I want to do at some point in the system.

**Comment by ZeiP** [comment]
Actually you're probably right, I haven't used the show by date all that much for now – but I certainly should, as that'd make the list much more manageable :)  I added a sentence of the Tickler view to the manual and therefore I think this issue can be closed. Thanks to @stderr-enst for making the very long-lived issue a reality!
