### ISSUE TITLE
CI doesn't run unit tests if feature tests fail

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1693]
Aside from being generally bad, this throws the Code Climate test coverage reporting way off. (It currently fluctuates between 84.4% and 29.3% depending on whether the features pass.)

**Comment by dnrce** [comment]
Might be addressed in Rails 5 using the upcoming test runner.

See https://github.com/rails/rails/issues/17708.

**Comment by ZeiP** [comment]
It seems this is not relevant any more, the tests should be working ok now.
