### ISSUE TITLE
blank.png missing

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1713]
I am using the current master branch f5c0c68285b0268842449adadd05674d7bcc07a8 (with 5f1772d4e041a4712e5ad5295fd71368e147c1f0 on top of that). The installation was 2.2.2, but I upgrade according to the documentation. All images work as expected, however the blank.png needed for the "delete dependency" function (editing a todo) does not exist:

`I, [2014-08-10T22:06:11.141407 #27460]  INFO -- : Started GET "/tracks/assets/blank.png" for 137.226.109.99 at 2014-08-10 22:06:11 +0200`
`F, [2014-08-10T22:06:11.146711 #27460] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/assets/blank.png"):`
`actionpack (4.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'`
`actionpack (4.1.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'`
`railties (4.1.4) lib/rails/rack/logger.rb:38:in `call_app'`
`railties (4.1.4) lib/rails/rack/logger.rb:20:in `block in call'`
`activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'`
`activesupport (4.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'`
`activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `tagged'`
`railties (4.1.4) lib/rails/rack/logger.rb:20:in `call'`
`actionpack (4.1.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'`
`rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'`
`rack (1.5.2) lib/rack/runtime.rb:17:in `call'`
`activesupport (4.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'`
`rack (1.5.2) lib/rack/sendfile.rb:112:in `call'`
`railties (4.1.4) lib/rails/engine.rb:514:in `call'`
`railties (4.1.4) lib/rails/application.rb:144:in `call'`
`/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'`
`/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'`
`/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'`
`/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'```

**Comment by C-Otto** [comment]
As I just had a similar problem and spent about an hour solving it: don't forget to delete track's cache (in tmp/). There might be snippets in there still referencing old/wrong URLS to missing assets.

**Comment by dnrce** [comment]
`rake tmp:clear` is the command you want.
