### ISSUE TITLE
Tag filter confuses todo and recurring todo

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1724]
On https://xxx/tracks/todos/tag/yyy# I see two entries for my tag named yyy. The first is correct, which is a repeating todo. It's ID is 4130, and the corresponding pattern is in the recurring_todos table with ID 110.

Below this (correct) entry I also see the wrong entry, which is a normal task with ID 110. It seems tracks does not use the taggable_type column when finding todos with a specific tag.

**Comment by dnrce** [comment]
Needs to be backported to 2.3

**Comment by matjack1** [comment]
Do you mean add the commit to the 2.3 branch? Do I need to open another PR for that?

**Comment by dnrce** [comment]
Nah, I'll take care of it. Thanks.

**Comment by matjack1** [comment]
:cool:
