### ISSUE TITLE
Possibility for third parties to add actions via email

### ISSUE THREAD

**Issue by momo-aux** [TracksApp/tracks#1734]
It would be great to give my Co Workers or my wife the possibility to send an E-Mail to a specific address or to go to the tracks page and add an action for me.

For E-Mail: 
Perhaps something like a whitelist check for an email account, if a new mail is from a person which is in my whitelist, then the mail is scanned for a keyword. 
Subject: Tracks: Buy apples
Body: The sweet ones

New action is added to my inbox with a specified tag (ex: External)

~~For cross posting:
If you enable cross posting for a account on the same server, this person can add actions to your inbox.~~

~~Wouldn't this be nice? Or is there already something like this and I just don't know.~~

**Comment by lrbalt** [comment]
This is possible today. 

We have the mailrunner you can configure to listen to emails from a whitelist of addresses. It does not scan for a specific keyword, but you can use @ and > to tell Tracks to add the email as a todo to a project and/or context

I have a specific email address which I use in the bcc of emails that I want to follow up. Or I forward a received email that needs action to this email so it gets added to Tracks.

I could share this email with my wife so she could add actions too, but I'm personally very hesitant about this :-)

I'd suggest closing.
