### ISSUE TITLE
configuration option "subdir" has no effect.

### ISSUE THREAD

**Issue by performantp** [TracksApp/tracks#1741]
The configuration option "subdir" in config/site.yml has no effect. 
Can someone confirm?

**Comment by lrbalt** [comment]
did you look at http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root

Especially the part about the headers the proxy needs to set. The relative_url_root is used by Rails to generate url's, not for processing requests.

**Comment by khyox** [comment]
For future reference, I would like to link this issue to [this thread/conversation](https://groups.google.com/forum/#!topic/tracksapp/RgMShcfosK4) in the Tracks mailing list, where a temporary workaround for using Tracks in a subdir under lighttpd is detailed.
