### ISSUE TITLE
Mobile header renders incorrectly in German locale

### ISSUE THREAD

**Issue by kralo** [TracksApp/tracks#1745]
With the german locale, in mobile view on i.e. 360x640 in firefox screen size testing (desktop), but on mobile firefox as well, the "new" button has two lines of text "Neue Aufgabe" and thus is higher than its counterparts.

Because the div #content uses a 'fixed' spacing of top margin 4em, sometimes the navigation bar overlays the content, which is quite ugly. Could the content div not be made floating?

**Comment by dnrce** [comment]
The #content div cannot (trivially) be made floating because the navigation header has a fixed position.

**Comment by C-Otto** [comment]
Maybe just use "+Aufgabe" or similar?
