### ISSUE TITLE
Links in the notes don't open a new browser tab

### ISSUE THREAD

**Issue by tmueller78** [TracksApp/tracks#1747]
Use case:
- I use Google Apps for Business, and regularly link to the tasks I have to take care of from within the notes.
- while links copied from the Mail tab are automatically recognized within tracks, they are not opened in a new tab
- so if I click on the link, it opens in the tab previously occupied by tracks.

**Comment by dnrce** [comment]
@tmueller78, I'm confused by the use case. Is it something specific to the interaction with Google Apps that's at issue? If so, please explain in more detail. Or is the particular use case not totally relevant and you'd just like Tracks to default all notes links to new tabs?

**Comment by tmueller78** [comment]
@dnrce, you're right, Google Apps for Business actually doesn't matter, but that's why it's very bothersome for me - it's part of my basic GTD workflow.
Default to new tab for all links would of course work, so please disregard the Google Apps part. ;(

**Comment by C-Otto** [comment]
This is still an issue for textile links (`"foo":http://bar`).
