### ISSUE TITLE
Database encryption

### ISSUE THREAD

**Issue by tmueller78** [TracksApp/tracks#1748]
For data privacy, I'd propose to encrypt the text in the database, at least by some simple method like ROT13 (http://en.wikipedia.org/wiki/ROT13). In order to allow other users to use one's installation, this would at least get rid of the other user's concern that one can read the data in plain text in the database anytime.
I don't know what's the best way to implement it, but my basic requirement is that it shouldn't be viewable in plain text in the database since it may contain sensible personal data.

**Comment by dnrce** [comment]
This is not best Rails practice, nor is it even good security practice. It also carries performance penalties because it breaks SQL functionality. Closing as "won't fix."

**Comment by lrbalt** [comment]
Agreed. If you want, you could store your sqlite database on an encrypted partition? Limit access to it using FUSE?
