### ISSUE TITLE
Intermittent StatsController test failure

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1760]
See https://travis-ci.org/TracksApp/tracks/jobs/50132324, which built 52481e0 at 2015-02-09 23:48:31Z.

```
1) Failure:
StatsControllerTest#test_actions_open_per_week_data [/home/travis/build/TracksApp/tracks/test/controllers/stats_controller_test.rb:252]:
there are actions in the first 17 weeks of this year.
Expected: 17
  Actual: 18
```

**Comment by C-Otto** [comment]
The job started a few minutes before midnight and took longer than that in total. If the day changed after creating the data ("given_todos_for_states", line 245) and before running the tested algorithm (":actions_open_per_week_data", line 248), this explains the issue.

Both the creation and the actual algorithm use "Time.zone.now", and, considering the load on the Travis machines and the persistence used to store the created todos in the database, the time passed between those two lines of code might be long enough to trigger the issue.

One could re-write the tests to deal with fixed (fake) time (as it is done in other places already), but I think this kind of issue is not worth the effort.

**Comment by C-Otto** [comment]
A similar problem just popped up:

https://travis-ci.org/TracksApp/tracks/jobs/58113608
```
StatsControllerTest#test_totals [/home/travis/build/TracksApp/tracks/test/controllers/stats_controller_test.rb:52]:
Expected: 2015-03-29 00:00:00 UTC
  Actual: 2015-03-28 00:00:00 UTC
```

**Comment by C-Otto** [comment]
```
TodoTest#test_load [/home/travis/build/TracksApp/tracks/test/models/todo_test.rb:25]:
Expected: "2015-04-05 00:00"
  Actual: "2015-04-04 00:00"
```
