### ISSUE TITLE
Edit / star icons invisible

### ISSUE THREAD

**Issue by ipec** [TracksApp/tracks#1761]
All Action icons (delete/edit/star) remain invisible (blank) in my browsers (firefox/palemoon/chrome).

system: 
banana pi
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty
Rubygems 1.8.23
ruby 1.9.3
WEBrick 1.3.1

Also is the current feature "Flexible views of your actions" supposed to work already?

**Comment by C-Otto** [comment]
Do you run tracks in a subdirectory, for example `http://somewhere/tracks/`?

**Comment by ipec** [comment]
Yes, I do:  /var/www/tracks.

Got an idea?

**Comment by ipec** [comment]
Solved by setting
---------------------------------------
config.assets.compile = true
--------------------------------------
 in /tracks/config/environments/production.rb
Finally all icons are there. :)
