### ISSUE TITLE
Overdue status should be inherited by dependencies

### ISSUE THREAD

**Issue by tomato42** [TracksApp/tracks#1779]
If a dependant is overdue it should mark the dependencies as overdue too.

The use case is when I have a action which has a specific deadline, but I'm not sure what needs to be done before the deadline task is possible to complete, I want the dependencies to inherit the deadline, so I see which tasks have a de-facto time limit vs ones that do not.

The other use case is when the deadline is not set in stone - inheritance of deadline would allow me to set a de-facto deadline for all tasks in a single place.

**Comment by C-Otto** [comment]
Related to #1413?

**Comment by tomato42** [comment]
Yes, it does seem to describe essentially the same functionality.
