### ISSUE TITLE
No way to Import backups (xml or yaml)

### ISSUE THREAD

**Issue by tspilk** [TracksApp/tracks#1822]
I see references in documents for a /tracks/data/import but these don't seem to function as far as I can tell. Is there some way to perform a manual import of backed up data?

**Comment by tspilk** [comment]
Found answer in #1702 
Currently round trip is not supported

**Comment by C-Otto** [comment]
@tspilk Could you also tell us where you read about this feature? Maybe we need to update the documentation?

**Comment by tspilk** [comment]
@@ C-Otto I searched the repo for import. There are several import-related docs here:

https://github.com/TracksApp/tracks/tree/620bcd136e9e63f47b27034e7b70765fd8200a50/app/views/data

**Comment by C-Otto** [comment]
These are available at `TRACKS_URL/data/import`, although I have no idea if they really work.

**Comment by lrbalt** [comment]
Import was disabled because of several issues. The contributer of the initial import code was not around anymore, so I disabled it before a release.
