### ISSUE TITLE
undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by flogo1982** [TracksApp/tracks#1826]
Hello,

When I try to add an action I have this error:

```
NoMethodError (undefined method `name' for nil:NilClass):
  lib/is_taggable.rb:56:in `block in _add_tags'
  lib/is_taggable.rb:50:in `each'
  lib/is_taggable.rb:50:in `_add_tags'
  lib/is_taggable.rb:35:in `block in tag_with'
  lib/is_taggable.rb:33:in `tag_with'
  app/controllers/todos_controller.rb:151:in `create'
```

and when I click on "Projects" I got a similar error:

```
NoMethodError (undefined method `name' for nil:NilClass):
  app/controllers/projects_controller.rb:32:in `block (2 levels) in index'
  app/controllers/projects_controller.rb:26:in `index'
```

I would appreciate any help! 
thx
Florian

**Comment by C-Otto** [comment]
Which version do you use?

**Comment by flogo1982** [comment]
I am using the version 2.2.3

**Comment by C-Otto** [comment]
Do you have additional information? Log files, step by step instructions? What action are you adding (and which new/old tags)? Did you recently rename a project or action (possibly to an empty string)?

**Comment by ZeiP** [comment]
Closing as no further information has been provided.
