### ISSUE TITLE
Discussion: JavaScript live updates

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1862]
The more I look into this, the more issues of wrong/missing live updates to the site I find. Furthermore, there seems to be A LOT of code duplication in the frontend and related code. What do you think about tackling these issues? Is it worth to collect individual bug reports? Is it even worth fixing those bugs?

**Comment by dnrce** [comment]
This is a pretty open discussion question for which the mailing list would be a better place.

That being said, I think this is all worthy of cleanup, but "worth fixing" is a more interesting question as it will mostly be part of the UI rewrite slated for 3.0. However, anything that can be captured in test case now would be a worthwhile addition to our test suite.
