### ISSUE TITLE
Allow static assets to be served without editing environment files

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1896]
Should not be served by default, but move the configuration into `site.yml`.

**Comment by mattr-** [comment]
Since serving static assets is a part of Rails configuration and our site configuration is loaded after Rails configuration, how would we end up solving this?

**Comment by dnrce** [comment]
`SITE_CONFIG` is populated at the top of application.rb. AFAIK this is before the environment-specific config is loaded, so environments/production.rb could easily use a config value to determine whether to serve static assets.

The goal here is to not require _versioned_ files to be edited to configure Tracks. Configuration of the app should not introduce a Git diff.

**Comment by mattr-** [comment]
:+1: to this. Working on a pull request now.
