### ISSUE TITLE
RSS Feeds return all Actions irrespective of settings

### ISSUE THREAD

**Issue by DeanCording** [TracksApp/tracks#1912]
If you view a RSS feed of say Actions due in 7 days or earlier, the feed contains all Actions instead of just those with a due date.  The iCal feed appears to be wrong as well. If you download the same as a text file you get the correct set of actions.

**Comment by ZeiP** [comment]
I was unable to reproduce this, so probably already fixed. Feel free to open a new issue if the problem re-occurs!
