### ISSUE TITLE
Spanish wrong translation

### ISSUE THREAD

**Issue by el-Salmon** [TracksApp/tracks#1913]
```toggle_contexts``` and ```toggle_contexts_title``` have a wrong translation in Spanish. Moreover, many strings have a missing translation to Spanish, like "in this project".

**Comment by C-Otto** [comment]
Do you want to provide/update Spanish translations? We could tell you how to do that easily.

**Comment by el-Salmon** [comment]
Yes, I could update Spanish translations in the es.yml file when I have time.

**Comment by C-Otto** [comment]
@el-Salmon Please have a look at this: https://github.com/TracksApp/tracks/wiki/Translating-Tracks

**Comment by C-Otto** [comment]
@el-Salmon Just a gentle reminder.

**Comment by el-Salmon** [comment]
Thanks for the reminder @C-Otto, I have an updated Spanish translation and I will make a pull request soon.

**Comment by dnrce** [comment]
Fixed in #1973.
