### ISSUE TITLE
Increase the maximum password length

### ISSUE THREAD

**Issue by SuperNascher** [TracksApp/tracks#1921]
The passwords are limited to 40 characters.
I don't like the limit, so is it possible to increase it?

**Comment by mattr-** [comment]
This is changeable on in `app/models/users.rb` on line 102. Change the
number 40 to a higher number. I believe the Devise authentication framework
uses 128 as an upper bound.

If you do this for your own installation, would you mind making a pull
request so we can fold it into the main codebase?

Thanks! :heart:

**Comment by dnrce** [comment]
Devise used to use 128 but now uses 72 because Bcrypt truncates anything beyond 72 characters: https://github.com/plataformatec/devise/commit/c7cc91cb65687e0325d817472a9da9b0c3894b41
