### ISSUE TITLE
Can't create new project with rest api

### ISSUE THREAD

**Issue by MFreeze** [TracksApp/tracks#1927]
Hi,

When I try to create a project with rest API with this command:

    curl -u user:passwd -H "Content-Type: text/xml" -d "<project><name>Test</name></project>" https://tracks.duvillie.eu/projects.xml -i -k 

I get a 400 http error.

I can give you the logs on the server : 

    I, [2015-09-14T00:30:20.992352 #19224]  INFO -- :   Rendered todos/check_deferred.js.erb (0.2ms)
    I, [2015-09-14T00:30:20.993210 #19224]  INFO -- : Completed 200 OK in 20ms (Views: 2.9ms | ActiveRecord: 1.8ms)
    I, [2015-09-14T00:35:47.874998 #19224]  INFO -- : Started POST "/projects.xml" for 88.123.185.241 at 2015-09-14 00:35:47 +0200
    I, [2015-09-14T00:35:47.885382 #19224]  INFO -- : Processing by ProjectsController#create as XML
    W, [2015-09-14T00:35:48.090280 #19224]  WARN -- : Can't verify CSRF token authenticity
    I, [2015-09-14T00:35:48.105993 #19224]  INFO -- : Completed 400 Bad Request in 220ms (ActiveRecord: 3.0ms)
     F, [2015-09-14T00:35:48.111691 #19224] FATAL -- : 
    ActionController::ParameterMissing (param is missing or the value is empty: project):
      app/controllers/projects_controller.rb:346:in `project_params'
      app/controllers/projects_controller.rb:174:in `create'

**PS** : the -k in the command only disables ssl verification of certificate (because of the self signed certificate of my server). I tried to disable https, and remove this option but the error is still the same.

Thank you

**Comment by dnrce** [comment]
"Test" is not valid data. Have you tried passing valid XML?
"<project><name>Build a treehouse for the kids</name></project>" is the
example in the documentation.

**Comment by MFreeze** [comment]
Yes I first tried with the given example, and got the same error

**Comment by dnrce** [comment]
Can you please provide a command exactly as you entered it (other than the
username/password), and the log output corresponding to that same command?

Have you tried this on the server itself, using localhost?

What is your server/proxy configuration providing SSL?

**Comment by MFreeze** [comment]
Here is the command for the project creation : 

    curl -u username:passwd -d "<project><name>Build a house</name></project>" https://tracks.duvillie.eu/projects.xml -i -k

This one is for the task creation : 

    curl -u username:passwd -H "Content-Type: text/xml" -d "<todo><description>Model in SketchUp</description><context_id>2</context_id><project_id>3</project_id></todo>" https://tracks.duvillie.eu/todos.xml -i -k

And I tried to run this one on the server: 

    curl -u username:passwd -d "<project><name>Build a house</name></project>" localhost:3001/projects.xml -i -k

But I get the same error and the same log.

For the configuration of my server do you want the tracks configuration file or those of nginx?

**Comment by MFreeze** [comment]
The problem has been solved with a fresh install.

**Comment by MFreeze** [comment]
I thought problem was solved with fresh install, but I was wrong. But this error this seems to be caused by supervisor, since when I manually launch webrick server everything works fine. 

When I use supervisor to launch the app, I can't get it working.

I close the issue.
