### ISSUE TITLE
Firefox won't load "mixed content" if running SSL server

### ISSUE THREAD

**Issue by sliwowitz** [TracksApp/tracks#1932]
Some javascript isn't loaded from an SSL server due to the use of full URL which include the wrong protocol (http instead of https). The problem seems to be that the root_url variable (or whatever it is) returns http://example.com even if called from https://example.com (this is on a SSL-only server). I don't know ruby at all, but some googling suggests this is a known issue, and there are suggestions to fix that.

Because of this, some crucial functionality (like pre-filling tags, contexts, etc.) is completely lost when servig Tracks from an SSL server (in Firefox 41, and likely a lot of other versions)

**Comment by dnrce** [comment]
How are you serving Tracks? Are you proxying it to add SSL or are you using something like Passenger?

**Comment by sliwowitz** [comment]
I'm on Apache + Passenger. 
(for the time being, I'm using a workaround - mod_substitute)

**Comment by sliwowitz** [comment]
This was a problem with Apache configuration. I have Tracks running on a subdomain vhost. Apache had SSL set in global options only (for all vhosts). Turns out you have to set "SSLEngine on" and all related directives (ciphers, keys, etc) explicitly in the vhost configuration, otherwise it won't pass the info down (that is - SSL would work correctly, but the application wouldn't know it's running on SSL).

**Comment by dnrce** [comment]
Glad you solved it. Thanks for following up!
