### ISSUE TITLE
Russian characters won't display properly

### ISSUE THREAD

**Issue by iarosenco** [TracksApp/tracks#1937]
I'm trying to use russian characters to name projects, next actions or to add notes without success. After I add a project for example, it displays the name as ?????? for a six letter russian word.

I tried enforcing mysql character set (as someone suggested) with these options in my.cnf:

```
[client]
default-character-set = utf8mb4

[mysql]
character-set-server = utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci
```

That also didn't help. What am I doing wrong?

Thanks,
Alex

**Comment by dnrce** [comment]
See what character set is used for your existing tables. Please share the output of the following queries:
```sql
select @@character_set_database, @@collation_database;
```
```sql
select
  t.table_name,
  ccsa.character_set_name,
  t.table_collation
from
  information_schema.tables t,
  information_schema.collation_character_set_applicability ccsa
where
  ccsa.collation_name = t.table_collation
    and
  t.table_schema='tracks'
order by 1;

**Comment by iarosenco** [comment]
mysql -e 'select @@character_set_database, @@collation_database;'
+--------------------------+----------------------+
| @@character_set_database | @@collation_database |
+--------------------------+----------------------+
| utf8mb4                  | utf8mb4_unicode_ci   |
+--------------------------+----------------------+

mysql> select
    ->   t.table_name,
    ->   ccsa.character_set_name,
    ->   t.table_collation
    -> from
    ->   information_schema.tables t,
    ->   information_schema.collation_character_set_applicability ccsa
    -> where
    ->   ccsa.collation_name = t.table_collation
    ->     and
    ->   t.table_schema = 'tracks'
    -> order by 1;
+-------------------------------------+--------------------+-------------------+
| table_name                          | character_set_name | table_collation   |
+-------------------------------------+--------------------+-------------------+
| contexts                            | latin1             | latin1_swedish_ci |
| dependencies                        | latin1             | latin1_swedish_ci |
| notes                               | latin1             | latin1_swedish_ci |
| open_id_authentication_associations | latin1             | latin1_swedish_ci |
| open_id_authentication_nonces       | latin1             | latin1_swedish_ci |
| preferences                         | latin1             | latin1_swedish_ci |
| projects                            | latin1             | latin1_swedish_ci |
| recurring_todos                     | latin1             | latin1_swedish_ci |
| schema_migrations                   | latin1             | latin1_swedish_ci |
| sessions                            | latin1             | latin1_swedish_ci |
| taggings                            | latin1             | latin1_swedish_ci |
| tags                                | latin1             | latin1_swedish_ci |
| todos                               | latin1             | latin1_swedish_ci |
| tolk_locales                        | latin1             | latin1_swedish_ci |
| tolk_phrases                        | latin1             | latin1_swedish_ci |
| tolk_translations                   | latin1             | latin1_swedish_ci |
| users                               | latin1             | latin1_swedish_ci |
+-------------------------------------+--------------------+-------------------+
17 rows in set (0.00 sec)

So it looks like the tables use latin1_swedish_ci . How do I change it to the proper one?

**Comment by dnrce** [comment]
For each table, run a statement like:
```sql
alter table contexts convert to character set utf8mb4;
```
Given your current defaults, the tables should all end up as `utf8mb4`/`utf8mb4_unicode_ci`.

**Comment by dnrce** [comment]
As a little more of an explanation, updating the defaults doesn't change what's already in the database. If your defaults were `latin1`/`latin1_swedish_ci` at the time you created the Tracks database, that's how that database remains configured until you manually alter it.

**Comment by iarosenco** [comment]
I ran the convert command for each table:

mysql> use tracks;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> alter table contexts convert to character set utf8mb4;
Query OK, 8 rows affected, 2 warnings (0.01 sec)
Records: 8  Duplicates: 0  Warnings: 2

mysql> alter table dependencies convert to character set utf8mb4;
Query OK, 6 rows affected (0.02 sec)
Records: 6  Duplicates: 0  Warnings: 0

mysql> alter table notes convert to character set utf8mb4;
Query OK, 3 rows affected (0.03 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> alter table open_id_authentication_associations convert to character set utf8mb4;
Query OK, 0 rows affected (0.03 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> alter table open_id_authentication_nonces convert to character set utf8mb4;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> alter table preferences convert to character set utf8mb4;
Query OK, 4 rows affected (0.02 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> alter table projects convert to character set utf8mb4;
Query OK, 27 rows affected, 2 warnings (0.02 sec)
Records: 27  Duplicates: 0  Warnings: 2

mysql> alter table recurring_todos convert to character set utf8mb4;
Query OK, 0 rows affected (0.03 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> alter table schema_migrations convert to character set utf8mb4;
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes

mysql> alter table sessions convert to character set utf8mb4;
Query OK, 37 rows affected, 2 warnings (0.03 sec)
Records: 37  Duplicates: 0  Warnings: 2

mysql> alter table taggings convert to character set utf8mb4;
Query OK, 61 rows affected, 4 warnings (0.04 sec)
Records: 61  Duplicates: 0  Warnings: 4

mysql> alter table tags convert to character set utf8mb4;
Query OK, 13 rows affected, 2 warnings (0.02 sec)
Records: 13  Duplicates: 0  Warnings: 2

mysql> alter table todos convert to character set utf8mb4;
Query OK, 137 rows affected (0.04 sec)
Records: 137  Duplicates: 0  Warnings: 0

mysql> alter table tolk_locales convert to character set utf8mb4;
ERROR 1071 (42000): Specified key was too long; max key length is 767 bytes
mysql> alter table tolk_phrases convert to character set utf8mb4;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> alter table tolk_translations convert to character set utf8mb4;
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> alter table users convert to character set utf8mb4;
Query OK, 4 rows affected (0.03 sec)
Records: 4  Duplicates: 0  Warnings: 0


This is how it looks now:

mysql> select
    ->   t.table_name,
    ->   ccsa.character_set_name,
    ->   t.table_collation
    -> from
    ->   information_schema.tables t,
    ->   information_schema.collation_character_set_applicability ccsa
    -> where
    ->   ccsa.collation_name = t.table_collation
    ->     and
    ->   t.table_schema = 'tracks'
    -> order by 1;
+-------------------------------------+--------------------+--------------------+
| table_name                          | character_set_name | table_collation    |
+-------------------------------------+--------------------+--------------------+
| contexts                            | utf8mb4            | utf8mb4_general_ci |
| dependencies                        | utf8mb4            | utf8mb4_general_ci |
| notes                               | utf8mb4            | utf8mb4_general_ci |
| open_id_authentication_associations | utf8mb4            | utf8mb4_general_ci |
| open_id_authentication_nonces       | utf8mb4            | utf8mb4_general_ci |
| preferences                         | utf8mb4            | utf8mb4_general_ci |
| projects                            | utf8mb4            | utf8mb4_general_ci |
| recurring_todos                     | utf8mb4            | utf8mb4_general_ci |
| schema_migrations                   | latin1             | latin1_swedish_ci  |
| sessions                            | utf8mb4            | utf8mb4_general_ci |
| taggings                            | utf8mb4            | utf8mb4_general_ci |
| tags                                | utf8mb4            | utf8mb4_general_ci |
| todos                               | utf8mb4            | utf8mb4_general_ci |
| tolk_locales                        | latin1             | latin1_swedish_ci  |
| tolk_phrases                        | utf8mb4            | utf8mb4_general_ci |
| tolk_translations                   | utf8mb4            | utf8mb4_general_ci |
| users                               | utf8mb4            | utf8mb4_general_ci |
+-------------------------------------+--------------------+--------------------+
17 rows in set (0.01 sec)

Those warnings are OK?

I tested and it works properly! Thank you!

**Comment by dnrce** [comment]
Looks good -- `schema_migrations` and `tolk_locales` don't need to be UTF-8.
