### ISSUE TITLE
Layout of "Edit recurring action" popup all messed up

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1938]
When I edit the properties of a recurring action, the shown popup is all messed up (CSS missing?). Could you check if this is also the case on your installations? I'm running a recent master build.

**Comment by mattr-** [comment]
This is what I see:
![screen shot 2015-11-12 at 2 16 59 pm](https://cloud.githubusercontent.com/assets/77174/11129972/1e655e88-8948-11e5-8eb1-ad82d488a41c.png)

Is this the issue you're talking about?

**Comment by C-Otto** [comment]
Exactly.

**Comment by mattr-** [comment]
:+1:
