### ISSUE TITLE
Deferred action with "Show Today"

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1940]
I have a recurring todo which is supposed to be shown today. Indeed, I see it in the tickler/deferred view/... with a box containing "Show Today". Why isn't that shown right now?

The `show_from` column contains `2015-11-21 20:55:22.2137`, which is in a few hours. I guess the H:M:s part of recurring todos should be set to midnight (or treated as such?).

**Comment by mattr-** [comment]
Since we're only dealing with dates for the 'show from' field, I agree that we should set that time to midnight (or perhaps another sensible default, like the start of the work day). Thanks for noticing.

**Comment by C-Otto** [comment]
This action also is not shown in the tickler, which seems to be cached/pre-rendered.
