### ISSUE TITLE
Only HTML content available

### ISSUE THREAD

**Issue by phsto** [TracksApp/tracks#1953]
I have installed Tracks 2.3. After this I started the thin in production mode. When I open the URL in the Browser I´m only available to see the "HTML content". Not all functions are available only a few.

Anyone know how to solve this Problem and get the correct "style"?

**Comment by C-Otto** [comment]
What do you mean with HTML content? Actual HTML tags, `<a href = ...>` and so on? Can you post a screenshot? Does the log file give error messages? Do you run tracks in a subdirectory (`http://server/SOMEWHERE/`)?

**Comment by epeisach** [comment]
When you say thin - do you mean as a stand alone environment? Did you change
config.serve_static_assets  to true in  config/environments/production.rb

**Comment by dnrce** [comment]
My guess is you missed either [Precompile Assets](https://github.com/TracksApp/tracks/blob/2.3_branch/doc/installation.md#precompile-assets) or step 5 of [Configure Variables](https://github.com/TracksApp/tracks/blob/2.3_branch/doc/installation.md#configure-variables), but please let us know if these don't fix your issue.

**Comment by phsto** [comment]
Login screen looks like this: http://www.directupload.net/file/d/4223/8k2kfhp7_png.htm
and after that like this: http://www.directupload.net/file/d/4223/gwra4hyg_png.htm

I started thin like this: rvm use 2.2.1@tracks && bundle exec thin start --environment production --port <Port> --prefix /tracks --daemonize

I precompiled the assets and their was no errors with this command: RAILS_ENV=production bundle exec rake assets:precompile

the configure variables are also set. 
config.serve_static_assets is set to true.

Maybe another Ideas?

Thanks.

**Comment by phsto** [comment]
No Idea?

**Comment by dnrce** [comment]
Is this actually Tracks 2.3 or is it 2.4devel? (If 2.3, which version, specifically?) Tracks 2.3.0 doesn't include thin, and isn't tested on Ruby 2.2.

**Comment by dnrce** [comment]
Ah, I see in your screenshot that it's 2.3.0.

What result do you get using the `rails server` command listed in the Tracks documentation?

Where does the `.htaccess` file come into play? Are you using Apache in front of this? If so, what is your Apache configuration? Please help us help you -- the whole context of your setup is pretty necessary to troubleshoot this.

More thorough HTML and log output would also be helpful. Can you post a gist of the full HTML output from e.g. the login page? It's useful to know what the `<img src` values are.

I'll also say that the mailing list is the correct forum for support issues like this.

**Comment by phsto** [comment]
I tried to to start thin server with ruby 1.9.3 and tried to connect WITHOUT HTTPS and it work.
The last Problem ist something with the HTTPS. If I can fix this it seems to work!!

I have to say sorry for my noobish englisch here. Im new on Github and improve my Englisch skills ;).

How can I contact this Mailing list?

Thanks!

**Comment by C-Otto** [comment]
Feel free to post in German, I'll translate :)

**Comment by phsto** [comment]
Okay Thanks C-Otto :)

Also Grundsätzlich habe ich es jetzt schonmal hinbekommen dass es funktioniert wenn ich es folgerndermaßen aufrufe:
http://domain.de/tracks
So wird alles richtig angezeigt. Allerdings funktioniert der Zugriff über 
https://domain.de/tracks
noch nicht. Ich habe tracks in meinem home Verzeichnis und eine .htaccess Datei unter html/tracks/ mit folgendem Inhalt:
RewriteEngine On
RewriteRule (.*) http://localhost:63247/tracks/$1 [P]
RequestHeader set X-Forwarded-Proto https

Letzteres sollte eigentlich immer das https erzwingen wenn ich es richtig verstehe. Zusätzlich habe ich in der Datei home/tracks/config/environments/prdoduction.rb folgendes eingetragen:

  # Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
    config.force_ssl = true

Somit müsste das mit SSL doch passen oder?

**Comment by C-Otto** [comment]
(I'll abbreviate a bit)

It now works with http, but not with https. There is a `.htaccess` file in the tracks directory:

```
RewriteEngine On
RewriteRule (.*) http://localhost:63247/tracks/$1 [P]
RequestHeader set X-Forwarded-Proto https
```

This should enforce https.

In `production.rb`: `config.force_ssl = true`.

Should this be enough to use SSL?

@phsto Gibt es zwei verschiedene Verzeichnisse für Tracks (html und home)?

**Comment by phsto** [comment]
Thanks Otto for transplate :)!

@C-Otto: Ja im home Verzeichnis liegen die ganzen Dateien da ist es sozusagen abgelegt bzw "installiert" auch wenn man das nicht so sagen kann. im Document Root (/html) liegt dann der Ordner tracks und beinhaltet die .htaccess

Hoffe es war verständlich erklärt sonst einfach fragen ;)

**Comment by C-Otto** [comment]
So in the current setup there is one directory `/html/tracks/` containing only the `.htaccess` file. This is the directory served by the webserver.

In addition to that tracks is installed/unpacked in `/home/tracks`.

@phsto Woher weiß der Webserver denn, dass die Dateien unter `/home/tracks` ausgeführt werden sollen? Gibt es irgendwo eine Verbindung, vielleicht in der Webserver-Config?

**Comment by phsto** [comment]
@C-Otto Das habe ich vergessen zu erwähnen sorry.
Ich thin dann folgendermaßen:
rvm use 1.9.3@tracks && bundle exec thin start --environment production --port <port> --prefix /tracks --daemonize

Damit weiß er ja dann über den Port und das Verzeichnis welches ich angeb wo es ausgeführt werden soll oder?

**Comment by C-Otto** [comment]
@phsto OK, wir reden also von Apache HTTPd für die HTTPs-Verbindung, und Thin auf Port 12345 lokal? Wenn du direkt auf http://...:12345 zugreifst geht es, mit HTTPs nicht?

**Comment by dnrce** [comment]
`force_ssl` makes the application _restrict_ itself to SSL, but it doesn't really do anything to _enable_ SSL. It does not need to be on in order to use SSL, but if you are using SSL, turning it on makes things a bit more secure.

**Comment by phsto** [comment]
@C-Otto genau. Wenn ich direkt auf https://....:12345 zugreife geht es prinzipiell von der Verbindung schon aber es werden dann keine Stylesheets oder ähnliches eingebunden sondern das Design ist spartanisch wie auf den Screenshots. Wenn ich auf das ganze über http:...:12345 aufrufe funktioniert alles so wie es soll inkl dem Design

@dnrce Okay thanks for this hint

**Comment by C-Otto** [comment]
OK, I have no idea what is happening here, but I can translate a bit.

Tracks runs using Thin, locally. Accessing it via http works as expected. Accesing it via https works, but the stylesheets are missing.

In addition to Thin, Apache HTTPd is used with the configuration shown above.

I guess that SSL/HTTPs should be disabled both in Tracks/Thin and in the Apache HTTPd redirection.

@phsto Probier mal bitte `config.force_ssl` und `RequestHeader set X-Forwarded-Proto https` aus deinen Konfigurationsdateien herauszunehmen.

**Comment by phsto** [comment]
@C-Otto Ich habe beides raus genommen und dann funktioniert es schon. Halt nur über http wo es ja theroretisch einfach ist mitzulesen wenn man will da ja nix verschlüsselt wird. Ist nur komisch dass es halt über HTTPs nicht tut weiß nicht was da der Unterschied für den Server für HTTP ist aber vielleicht klappt das einfach mit thin nicht so gut im Zusammenspiel, wie du schon oben erwähnt hast.

**Comment by phsto** [comment]
@C-Otto Ich habe bei Firefox mal genauer nachgeschaut wenn ich mich über HTTPs verbinden will. Wenn ich links oben im URL Feld mir das Zertifikat anzeigen lassen will, sagt er mir 
"Teile dieser Seite sind nicht sicher, dies können z.B. Grafiken sein. Obwohl Firefox Inhalte blockiert hat, enthält diese Seite noch unsicher Inhalte (wie z.B. Grafiken)."

Also hat er wohl ein Problem die Grafiken als sicher einzustufen?

**Comment by C-Otto** [comment]
@phsto So wie ich das sehe, ist alles bis zum Apache HTTPd verschlüsselt. Innerhalb deines Rechners, also vom Apache HTTPd zu Tracks, allerdings nicht. Das sollte aber kein Problem sein, oder? Wenn du HTPPs auch für Thin benutzt, muss Thin entsprechend konfiguriert sein. Zusätzlich musst du aber auch den Apache HTTPd (Proxy) richtig konfigurieren. Irgendwo hier wird dann wohl das Problem sein. Was dein Firefox da bemängelt, kann ich von hier nicht nachvollziehen. Das wird aber alles kein Tracks-Problem sein, denke ich...

**Comment by mattr-** [comment]
Is this resolved now?

**Comment by C-Otto** [comment]
I'd say it is not related to Tracks, as it only is an issue in combination with Apache HTTPd. I strongly assume that the proxy/redirection in combination with HTTPs/SSL is the issue.

**Comment by mattr-** [comment]
Ok, then, I'll close this for now, and any further questions can be sent to the mailing list at tracks-discuss@googlegroups.com
