### ISSUE TITLE
Privacy issue: user can see project tags from other users

### ISSUE THREAD

**Issue by habernal** [TracksApp/tracks#1955]
Version 2.3.0

Repro:
- Have a user A with some projects and tags
- Create a new user B
- Sign up as user B
- Go to Projects page and start filling the form for adding new project
- Start typing into the field "Default tags (optional)", you will get suggestions of project tags from user A

I guess it's not an intended behavior.

**Comment by ZeiP** [comment]
There seems to be a TODO comment in the respective controller (todos_controller.rb#tags). However, unlike contexts, tags don't currently have an owning user defined, so I think this requires also changing the schema and considering how to migrate – should all current tags be shown to everyone and new tags have the creating user recorded?

**Comment by habernal** [comment]
I believe that Contexts, Projects as well as Tags should be user-bound (and the existing ones perhaps migrated in the long-run).

**Comment by mattr-** [comment]
Contexts and Projects are already user-bound. Tags are the only things that aren't currently.
