### ISSUE TITLE
Frequent relogins?

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1963]
Sorry for being vague. I have the impression that tracks asks me to login far more often than what I'm used to. I'm pretty sure my previous sessions lasted longer than a day. Currently, I have to re-login every day for every device I use. Did anything corresponding to this change recently? Is this expected behavior?

**Comment by mattr-** [comment]
I'm seeing this as well and it's not expected behavior. The session cookies aren't supposed to expire until a year later, but is somehow being invalidated.

No idea what caused this though.
