### ISSUE TITLE
Signup page: Cookie overflow

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#1984]
The singup page triggers a cookie overflow error when creating an invalid user. Removing `session['new_user'] = user` (https://github.com/TracksApp/tracks/blob/master/app/controllers/users_controller.rb#L84) helps, but I do not know what this line is supposed to do.

`ActionDispatch::Cookies::CookieOverflow`

**Comment by dnrce** [comment]
Related to #1751.

**Comment by ZeiP** [comment]
I discovered the same problem and fixed it by removing the session line in #2430, so this should be fixed.
