### ISSUE TITLE
Use Gitter for chat?

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#1991]
I've looked a bit at [Gitter](https://gitter.im/) as a replacement for our IRC channel. The big advantage it would have for users like me who are only infrequently signed in is preservation of history, and in general it may be more accessible than IRC for more casual users/developers. Thoughts?

Here's what would be our channel: https://gitter.im/TracksApp/tracks

**Comment by C-Otto** [comment]
I don't like that I need to create an account to be able to chat.

**Comment by dnrce** [comment]
It uses GitHub auth, so it isn't really a new account.

**Comment by C-Otto** [comment]
OK, looks good to me.

**Comment by mattr-** [comment]
:+1:

**Comment by dnrce** [comment]
Gitter has been acquired by GitLab and will be open-sourced: https://about.gitlab.com/2017/03/15/gitter-acquisition/

**Comment by ZeiP** [comment]
The Gitter channel is in use, so perhaps we can close down this issue.
