### ISSUE TITLE
ruby relocation issue when installing on Arch Linux ARM

### ISSUE THREAD

**Issue by jackjackk** [TracksApp/tracks#2001]
When installing using [this script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tracks#n44), I get

"ruby: relocation error: /tmp/pacaurtmp-jack/tracks/src/TracksApp-tracks-4070f4e/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.16/lib/mysql2/mysql2.so: symbol mysql_get_client_info, version libmysqlclient_16 not defined in file libmysqlclient.so.18 with link time reference"

any idea on how I could solve this issue?

Thanks

**Comment by mattr-** [comment]
it looks like the bundle process is picking up an older version of libmysqlclient but when running tracks, it's pulling in an newer version of the library. without knowing more about your setup, not sure we can help too much.

**Comment by jackjackk** [comment]
thanks mattr.
first, I get the same error on a clean install of archlinux arm (before I thought I messed up with rvm).
second, I don't get any error with the same script on a clean install of archlinux (not the arm version).
third, please find at the link below the output of some random commands (not very familiar with ruby on rails). please let me know what else could be useful to debug this. I would be very interested in using your app.

https://gist.github.com/jackjackk/c7ec564a9f2472b09222

thanks

**Comment by ZeiP** [comment]
Closing this as a four years old support ticket is probably no longer relevant. Docker-based installation is now preferred, so a similar problem should not occur there.
