### ISSUE TITLE
UI: Missing space in search result page

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#2003]
"4Todos matching query"

**Comment by rbndickson** [comment]
Hi, I am a relatively new Rails dev and am interested in helping this project. I have made my own sites but nothing near this complexity.

I'm also new to open source so don't know exactly how things work.

Is it best to take on some easyish issues such as this one, fix them and create PRs?

Thanks,
Robin

**Comment by mattr-** [comment]
Yup, that's exactly the way to do it. 😃






On Fri, May 13, 2016 at 10:43 AM -0700, "Robin Dickson" <notifications@github.com> wrote:












Hi, I am a relatively new Rails dev and am interested in helping this project. I have made my own sites but nothing near this complexity.



I'm also new to open source so don't know exactly how things work.



Is it best to take on some easyish issues such as this one, fix them and create PRs?



Thanks,

Robin

**Comment by rbndickson** [comment]
Great, thanks for the quick reply!

For small fixes is it better to create 1 PR each, or to group a few into 1 PR?

**Comment by C-Otto** [comment]
In my experience it is better to have separate PRs. Sometimes you don't quite get it right due to some tiny mistake or misunderstanding. In such situations all the other PRs could you through, while a big PR gets blocked and over time gets more confusing.

**Comment by rbndickson** [comment]
That makes sense 👍
