### ISSUE TITLE
master broken for subdir installations

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#2011]
Introduced with d0c4fee7e4e9c040daa6163dadffff0689e69b33.

The change hardcodes the path to start with '/' whereas it should start with '/tracks/' in my case.

@mattr- could you look into this?

**Comment by dnrce** [comment]
Caused by #1986

**Comment by dnrce** [comment]
Achieving the goal of #1986 (no protocol or base URL) should be as simple as changing `root_url` to `root_path` in the code before this change.

**Comment by C-Otto** [comment]
That works for me, yes. Could you test for the https/proxy/... case?

**Comment by mattr-** [comment]
Fixing with #2012. I'm not running Tracks right now due to my own laziness in setting it up after a server upgrade, so I'd rather just unbreak it and then swing around and fix it properly later.

**Comment by C-Otto** [comment]
Thank you

**Comment by C-Otto** [comment]
As a note: `root_path` does not work when creating a new action inside the `.../projects/1` page.
