### ISSUE TITLE
master: "Add a new recurring action" UI messed up

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#2024]
In a somewhat recent commit (Rails 4.2?) the UI degenerated as shown in the picture.

![recurring](https://cloud.githubusercontent.com/assets/344948/16281238/b1cf8312-38c3-11e6-9e0f-3303eec652b8.png)

**Comment by dnrce** [comment]
Bisecting shows that this broke in d7d86446c028495312b98bb888643bead4425a14.

**Comment by dnrce** [comment]
Specifically, this seems to have been due to the sprockets change from 2.11.3 to 3.6.0.

**Comment by dnrce** [comment]
Might be something in here: https://github.com/rails/sprockets/blob/v3.6.0/UPGRADING.md
