### ISSUE TITLE
Upgrade to Rails 5.0

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#2031]
See http://guides.rubyonrails.org/upgrading_ruby_on_rails.html.

Currently blocked by cucumber/cucumber-rails#319.

**Comment by mathieujobin** [comment]
cucumber-rails v1.4.4 released with rails 5.0.0 support

**Comment by dnrce** [comment]
Thanks, @mathieujobin!

**Comment by dnrce** [comment]
I'm currently one failing test away from having a PR for this.

**Comment by mattr-** [comment]
Closed with #2121 instead of #2084.
