### ISSUE TITLE
REST API: /done.xml doesn't work.

### ISSUE THREAD

**Issue by RedNifre** [TracksApp/tracks#2034]
/done.xml responds with this:

<?xml version="1.0" encoding="UTF-8"?>
<hash>
  <status>500</status>
  <error>Internal Server Error</error>
</hash>

Server logs show nothing.

**Comment by ZeiP** [comment]
The route in /done points to stats#done, which doesn't have XML support. I wonder if the documentation is trying to point to /todos/done.xml instead?

**Comment by mattr-** [comment]
🤦‍♂ that's likely what's going on here.

**Comment by ZeiP** [comment]
Added a PR fixing this at #2209.

**Comment by mattr-** [comment]
Closed after #2209 was merged.
