### ISSUE TITLE
REST API: /hidden.xml does not exist

### ISSUE THREAD

**Issue by RedNifre** [TracksApp/tracks#2035]
The /hidden.xml call mention in the documentation returns the standard 404 html page.

Might be because I neither have hidden contexts nor hidden projects.

**Comment by ZeiP** [comment]
I think it's because the route has been removed from config/routes.rb in commit a83c8b3f928b18f8029aaea4926b1f8f2a22f6ff.

**Comment by ZeiP** [comment]
I created a PR fixing this: #2204

**Comment by ZeiP** [comment]
Fixed.
