### ISSUE TITLE
REST API: /calendar.xml return nil-classes

### ISSUE THREAD

**Issue by RedNifre** [TracksApp/tracks#2036]
/calendar.xml returns this:

<?xml version="1.0" encoding="UTF-8"?>
<nil-classes type="array"/>

My calendar is empty. Why does it say nil-classes?

**Comment by ZeiP** [comment]
It seems that any empty XML has ”nil-classes” as the root element. This seems like a bug, but affects all APIs, not just /calendar.xml.

**Comment by ZeiP** [comment]
I found a fix for this. It can be found in pull request #2205

**Comment by ZeiP** [comment]
Fixed.
