### ISSUE TITLE
No port access to ruby tracks vagrant, virtualbox, ubuntu server

### ISSUE THREAD

**Issue by bluebaroncanada** [TracksApp/tracks#2042]
I have a vagrant installation ubuntu/trusty64 running Ruby. I'm trying to run a tracks server. The server launches and I can access it locally.

```
=> Booting Thin
=> Rails 4.2.6 application starting in production on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on localhost:3000, CTRL+C to stop
```
I can obviously `ssh localhost:2222` which is forwarded to `22`. I can `telnet 192.168.33.10 22`. I get the banner `SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7`

I can `curl -X GET localhost:3000` while sshed into the box.

&lt;html>&lt;body>You are being &lt;a href="http://localhost:3000/login">redirected&lt;/a>.&lt;/body>&lt;/html>

But I cannot connect in any way outside the box. 

`telnet 192.168.33.10 3000`
`Connecting To 192.168.33.10...Could not open connection to the host, on port 3000: Connect failed`
In my vagrantfile I have: `config.vm.network "forwarded_port", guest: 3000, host: 3001`

I cannot even `telnet localhost 3001` on my host. I have also visually confirmed that this rule went into effect in the Virtual Box config.

Any ideas would be much appreciated.

**Comment by C-Otto** [comment]
I don't think this is an issue with tracks. However, based on my experience with Vagrant and VMs, I'd double-check any (personal) firewall you might use.

**Comment by bluebaroncanada** [comment]
I have turned my firewall completely off.   Both private and public.  I also iptables -L on the vagrant box and I have no rules.

**Comment by bluebaroncanada** [comment]
Right now when tracks loads up it says it's listening to localhost:3000.  Is there any way to put that on the external interface?

**Comment by bluebaroncanada** [comment]
by passing -b and my interface I've sort of resolved this issue.
