### ISSUE TITLE
All assets 404

### ISSUE THREAD

**Issue by bluebaroncanada** [TracksApp/tracks#2043]
I just finished installing tracks.  For some reason all the assets 404.  I get html, but no assets.
Ubuntu 14.04.  Ruby 2.3.0.

![image](https://cloud.githubusercontent.com/assets/5856849/18515088/14aa9fd2-7a62-11e6-8b66-9ecf19666734.png)

**Comment by mattr-** [comment]
If you're running in production mode, please make sure you've precompiled
all the assets by running `RAILS_ENV=production bundle exec rake
assets:precompile`​

**Comment by bluebaroncanada** [comment]
I have and the assets do exist under the public/assets directory.

**Comment by mattr-** [comment]
Do you have nginx or apache sitting in front of thin or webrick or whatever
you're using to run the rails app? If not, have you turned on the option
(either in the rails config or in site.yml, depending on the version of
Tracks) to have your app server serve out the static assets?
`config.serve_static_assets` is the config key, if I remember correctly.

**Comment by bluebaroncanada** [comment]
I redid the precompile and it still isn't working.
I also checked the permissions of the public and assets directories and they're both vagrant:vagrant ownership 
drwxrwxr-x 3 vagrant vagrant 4096 Sep 14 01:30 public/
drwxrwxr-x 5 vagrant vagrant 12288 Sep 14 09:59 assets

and here's one of the assets in the assets directory

-rw-rw-r-- 1 vagrant vagrant 235310 Sep 14 01:28 application-9d4b409f1619fa607e6a8da41a51d7354ca59f559e13d9c636a221da696f4716.css
that one won't load

**Comment by bluebaroncanada** [comment]
vagrant@vagrant-ubuntu-trusty-64:/var/www/tracks$ grep -R serve_static_assets *
config/site.yml:# serve_static_assets: false

**Comment by bluebaroncanada** [comment]
No I do not have apache.  Here's my vagrant provisioning script:
https://gist.github.com/bluebaroncanada/e322517eff09be8651e1a1a5ae68be60

**Comment by mattr-** [comment]
if you set serve_static_assets needs to be `true` that should fix your
issue.

**Comment by bluebaroncanada** [comment]
Sorry.  I'm having trouble understanding your last message.  I did not set serve_static_assets.  I'm running in production mode.

**Comment by mattr-** [comment]
You need to set `serve_static_assets` to `true` in `config/site.yml` and
restart your app server

**Comment by bluebaroncanada** [comment]
<3
