### ISSUE TITLE
Finally, offline mode and responsive design

### ISSUE THREAD

**Issue by tmueller78** [TracksApp/tracks#2047]
Hi everybody!

I don't want to spam here, but I couldn't find any way to contact Dan Rice directly and I'm not a github pro.
I loved tracks, but was quite bothered by the missing offline mode, the dated design, no native apps and so on. Therefore, I spent some money on a developer and a lot of time on creating a new GTD app which gets rid of these and some other problems: clearmind.io
We just launched this week in public beta and would appreciate any feedback; of course, feature-wise, we're far from finished, but everything you really need is already there. Including import. :)

While we're going in the direction of SaaS to earn back the investment eventually, anybody who's been involved with Tracks up to now will get free access to all features for life - just get in touch with me: clearmind@tmt-beratung.de :)

**Comment by C-Otto** [comment]
[clearmind.io](http://clearmind.io)

I suggest to proof-read the testimonials :)

**Comment by tmueller78** [comment]
Even superheroes in disguise need some help with the language at times... ;P
Thanks - fixed! :)

**Comment by C-Otto** [comment]
Could you please close this issue? This is not related to this project.

**Comment by tmueller78** [comment]
Closing it in a moment. Is there any board where I can reach the tracks users?

**Comment by C-Otto** [comment]
https://groups.google.com/forum/#!forum/TracksApp
