### ISSUE TITLE
keys being duplicated leading to app crash

### ISSUE THREAD

**Issue by RabidBurn** [TracksApp/tracks#2053]
Hello,
Sometimes my tracks app will crash with seemingly no cause (at least, as far as I can tell).

It throws this error:
App 3252 stderr: /home/nonroot/.rvm/gems/ruby-2.3.3/gems/htmlentities-4.3.2/lib/htmlentities/mappings/expanded.rb:465: warning: key "inodot" is duplicated and overwritten on line 466
App 3252 stderr: /servers/tracks/app/models/recurring_todos/abstract_recurring_todos_builder.rb:80: warning: key :target is duplicated and overwritten on line 85

in the apache2 error.log

Eventually, it comes back up on it's own, but no number of apache2 or passenger restarts will make it come back up.

I can provide any other info that might be useful, just let me know what you need.

Thanks.

**Comment by mattr-** [comment]
Are you using Tracks with the English language or a different language?

**Comment by RabidBurn** [comment]
Yes, English

**Comment by RabidBurn** [comment]
Restarting the server fixes this but that's far from an ideal solution...

**Comment by RabidBurn** [comment]
I've just discovered and replaced a bad stick of RAM in my server, which might have been the root cause of the problem. I'm going to close this issue for now, but I'll reopen it if the crash happens again.

**Comment by sccarr** [comment]
Hi, I have the same issue actually, and I am using a local server.  Any ideas?

**Comment by ZeiP** [comment]
@sccarr, could you please open a new issue with fresh logs? You should also mention your environment (app version etc.)

**Comment by sccarr** [comment]
Thanks, I actually figured it out myself.

**Comment by C-Otto** [comment]
@sccarr please share your insights with us!
