### ISSUE TITLE
Editing project settings with special characters in project name

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#2077]
Related to #2051 

When I edit the project settings (for example by editing the description), after saving the project name in the form is wrong (escaped HTML).

**Comment by RyanTruran** [comment]
I found the bug and solved the issue, pull request has been made.

**Comment by C-Otto** [comment]
Which one? Please reference it with a # sign. And thank you :)

**Comment by RyanTruran** [comment]
#2096
