### ISSUE TITLE
Share Task list with group/create group to-do list

### ISSUE THREAD

**Issue by thenodemaster** [TracksApp/tracks#2080]
We run Tracks 2.3.0 on Ubuntu Server 16.04 and I see that the ability to share lists among users was added in V2, but I cannot figure out how to enable that feature.  We have 3 people who need access to the same list and allowed to check off tasks on said group list.  I could not find anything in the wiki or docs regarding this and a Google search came up empty.  Any assistance with this would be greatly appreciated.

**Comment by mattr-** [comment]
Tracks doesn't have this feature.

Closing this one, as I answered a similar query from the mailing list.
