### ISSUE TITLE
new release for Ruby 2.2 or above

### ISSUE THREAD

**Issue by AndCycle** [TracksApp/tracks#2092]
as Ruby 2.1 has announced end support at March 31, 2017,
many distros has abandoned it from repo,

now I have to cut from master to keep it running ...

**Comment by mattr-** [comment]
There's nothing preventing you from running the current release with Ruby
2.2 or later. If there is, please let us know.

**Comment by AndCycle** [comment]
@mattr- thanks for the acknowledge, 
so I do tried and hit by https://github.com/rubys/nokogumbo/issues/25
then I have to manual workaround binutils.

**Comment by AndCycle** [comment]
it's fine if you wanna close this issue,
after some minor fix around master I can keep it going.

**Comment by mattr-** [comment]
Sounds like we need to release a new version though. I'll add it to my todo list and close this issue.
