### ISSUE TITLE
count > 0 should be exists?

### ISSUE THREAD

**Issue by lelelelemon** [TracksApp/tracks#2094]
```
tracks/app/models/user.rb:66:                todos_in_project.reject{ \|p\| p.todos.active.count > 0 }
--
tracks/app/models/message_gateway.rb:128:    return parts.count > 0 ? parts[0].decoded.strip : ""
tracks/app/controllers/recurring_todos_controller.rb:15:    @no_recurring_todos = @recurring_todos.count == 0
tracks/app/controllers/recurring_todos_controller.rb:16:    @no_completed_recurring_todos = @completed_recurring_todos.count == 0
```
since exists? issues query select 1 instead of select count(*)

**Comment by RyanTruran** [comment]
What exactly are you trying to do?

**Comment by mattr-** [comment]
I agree with this. `exists?` is a better method to use here when looking for a count > 0 because of the way the query is structured. `SELECT 1` in SQL will naturally be faster than `SELECT count(*)` because the SQL engine won't have to perform any calculations when using `SELECT 1`
