### ISSUE TITLE
Running tracks under a url subdirectory

### ISSUE THREAD

**Issue by Jhmanton** [TracksApp/tracks#2100]
When I used the "subdir" option in site.yml, it correctly placed /tracks in front of static assets. However, it did not change the page urls, so for example, "/login" was used as the action on a form, rather than "/tracks/login". This meant I was unable to set nginx to proxy http://some.address/tracks to localhost:3000 and have it work.

**Comment by mattr-** [comment]
If you're going to proxy the tracks application server through nginx, you should set it up to serve the static assets and not use the `subdir` option in `site.yml`.

I'm going to deprecate the `subdir` option and remove it in a later version of Tracks, and add some better docs for how to proxy Tracks through nginx as this is the recommended way to do it, IMHO.

**Comment by Jhmanton** [comment]
Please note that the issue ( #2100 ) was not the static assets (they worked properly!) but the page urls. What is useful to have, is the ability to proxy tracks not at http://some.address/ but at http://some.address/tracks, for example. Without a "subdir"-like option, this might not be (easily) possible with nginx (without going into rewrite rules). If you have it working successfully though, please share the nginx config.

**Comment by texnofobix** [comment]
I currently have the following working (except a font-awesome asset not loading properly via css) with:
```nginx
        location /tracks/ {
                proxy_pass http://10.0.0.1:3000/;
                sub_filter '"/' '"/tracks/';
                sub_filter 'http://10.0.0.1:3000/' 'https://example.org/tracks/';
                sub_filter_once off;
        }
```
Trying to modify the css seems to break the content.
