### ISSUE TITLE
Project is dead

### ISSUE THREAD

**Issue by tomato42** [TracksApp/tracks#2105]
There is "I don't have much time to work on it" and there is "my dependencies have [18 security issues](https://gemnasium.com/TracksApp/tracks) open"

There is "I'd like to work more on it" and there is "the project doesn't build in CI for over [half a year](https://travis-ci.org/TracksApp/tracks/builds)"

There is "I'd like to see more help from the community" and there is "[pull requests](https://github.com/TracksApp/tracks/pull/2071) changing 3 lines total waiting over a year for a single comment"

When you need to manually update the `Gemfile` to even run it on Fedora _26_ in _May 2018_, the project can only be described as dead.

It was a nice ride, the application was really awesome, but it's time to move on.

<details>
    <summary>edited Gemfile</summary><p>

```ruby
source 'https://rubygems.org'

gem 'rails', '~> 4.2.10'
gem 'sass-rails', '~> 4.0.3'
gem 'coffee-rails', '~> 4.0.1'

#gem 'json'

# todo: remove xml api
gem 'actionpack-xml_parser', '~> 1.0.1'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', '~> 0.12.3'

gem 'uglifier', '~> 2.5.3'

gem 'jquery-rails', '~> 3.1.2'

# you may comment out the database driver you will not be using.
# This will prevent a native build of the driver. Building native drivers is not
# always possible on all hosters
gem "sqlite3", "~> 1.3.9"
gem "mysql2", "~> 0.3.16"

gem "RedCloth", "~> 4.2.9"
gem "sanitize", "~> 3.0.2"
gem "will_paginate", "~> 3.0.7"
gem "acts_as_list", "~> 0.4.0"
gem "aasm", "~> 3.4.0"
gem "htmlentities", "~> 4.3.2"
gem "swf_fu", "~> 2.0.4"
gem "rails_autolink", "~> 1.1.6"
gem "cache_digests", "~> 0.3.1"

# To use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 1.2'

group :development do
  gem "spring", "~> 1.1.3"
  gem "spring-commands-cucumber", "~> 1.0.1"
  gem "yard", "~> 0.8.7.4"

  gem 'tolk', '~> 2.0.0'

  gem "bullet", "~> 4.13.2"
  gem "rack-mini-profiler", "~> 0.9.2"
  gem "rack-dev-mark", "0.7.3"
  gem "activerecord-deprecated_finders", "~> 1.0.3"
end

group :test do
  gem "factory_girl_rails", "~> 4.4.1"
  gem "capybara", "~> 2.4.3"
  gem "cucumber-rails", "~> 1.4.1", :require => false
  gem "rspec-expectations", "~> 3.1.2"
  gem "database_cleaner", "~> 1.3.0"
  gem "mocha", "~> 1.1.0", :require => false

  gem "aruba", "~> 0.6.1", :require => false

  # Note that > 2.14 has problems, see:
  # https://code.google.com/p/selenium/issues/detail?id=3075
  gem "selenium-webdriver"

  # uncomment to use the webkit option. This depends on Qt being installed
  # gem "capybara-webkit"

  # uncomment to be able to make screenshots from scenarios
  #gem "capybara-screenshot"
  #gem "launchy"

  gem "simplecov", "~> 0.9.1"
  # get test coverage info on codeclimate
  gem "codeclimate-test-reporter", "~> 0.4.1", group: :test, require: nil
end
```

</p></details>

**Comment by iangreenleaf** [comment]
What's the point of this issue? If you're unhappy with the progress of the project, offer some solutions to help rectify some of the problems. If you're just here to cast blame at the maintainers (who I'd like you to remember do this for free in their free time), that doesn't seem very necessary.

**Comment by tomato42** [comment]
It's a warning to others, using unmaintained software on the web is dangerous. Don't do it, that's how botnets are created.

There are multiple examples of people stepping up to help and [hitting walls](https://groups.google.com/forum/#!topic/TracksApp/1fGdqjezg9Y) and unresponsive maintainers (just look at PR tab), why should I think that my effort would be different?

yes, maintainers do this on their own time, but to receive contributions they need to keep the minimum of infrastructure running, like CI – not having time to fix it for over half a year means they will have no time to review and merge contributions.

this is an environment that is hostile to contributors

(I'm telling this because _I cared_ about this project, so please, without the "doesn't seem very necessary")

**Comment by C-Otto** [comment]
As the one who complained in the past (visible in some of the links above), I fully agree that this is an issue. However, I don't think that this is a constructive bug report and I also do not see how this issue can be solved.

**Comment by mattr-** [comment]
I thought I had written this somewhere else publicly but I gave myself a deadline of August 1st to get this project back up and running and in a place where I can work on it and more easily accept contributions again. #2103 is the first step of that (but of course I really broke the CI in the process). 

If August 1st comes and goes and I don't think I'll be able to continue this project and there aren't folks who are willing to continue it, then I'll be explicitly marking it as unmaintained after then.
