### ISSUE TITLE
Token vs. Password for API access

### ISSUE THREAD

**Issue by mattr-** [TracksApp/tracks#2203]
Got a report from a user on the mailing list where they were required to use their password instead of the their API token for API access. Need to confirm the paths and figure out what's going on here and see if we're missing token based authentication somewhere.

**Comment by ZeiP** [comment]
Yep. I tried to use in place of the password, but that didn't work. I took a peek at the code, and it seems that the token isn't really meant to work with the RSS API. Only a few of the controllers providing RSS APIs use login_or_token_required decorator, others use just the default login_required, which doesn't allow tokens.

When I do this, I'm able to use the token:
`diff --git a/lib/login_system.rb b/lib/login_system.rb
index 1d3f6b0a..a3dfe2df 100644
--- a/lib/login_system.rb
+++ b/lib/login_system.rb
@@ -71,7 +71,7 @@ module LoginSystem
   end
 
   def login_or_feed_token_required
-    if ['rss', 'atom', 'txt', 'ics'].include?(params[:format])
+    if ['rss', 'atom', 'txt', 'ics', 'xml'].include?(params[:format])
       if user = User.where(:token => params[:token]).first
         set_current_user(user)
         return true
`

With that change, the following query works:

`curl -H "Content-Type: text/xml" 'https://tracks.example.org/context/1/todos.xml?token=TOKEN' -i`

If we wanted to allow token authentication also for /tickler.xml, this would do it:

`diff --git a/app/controllers/todos_controller.rb b/app/controllers/todos_controller.rb
index eb7be53d..ea9277cd 100644
--- a/app/controllers/todos_controller.rb
+++ b/app/controllers/todos_controller.rb
@@ -1,7 +1,7 @@
 class TodosController < ApplicationController
 
-  skip_before_action :login_required, :only => [:index, :tag]
-  prepend_before_action :login_or_feed_token_required, :only => [:index, :tag]
+  skip_before_action :login_required, :only => [:index, :tag, :list_deferred]
+  prepend_before_action :login_or_feed_token_required, :only => [:index, :tag, :list_deferred]
   append_before_action :find_and_activate_ready, :only => [:index, :list_deferred]
 
   protect_from_forgery :except => :check_deferred
`

But the actual question is, should we use the same token for API access also. URL request parameters are often logged in HTTP server logs, so it might make sense to use basic authentication scheme for the REST API; however, then it would perhaps also make more sense to have one token for the feeds and another one for the API. Thoughts?

**Comment by mattr-** [comment]
I'm ok with the changes you've proposed here as an initial first step, as the whole entire authentication system is probably in need of an overhaul.

>however, then it would perhaps also make more sense to have one token for the feeds and another one for the API.

Rather than separating feed access and API access, I'd rather look at it as programmatic access vs non-programmatic access. I agree that we should update to use basic auth all around, rather than including the token in the URL as a parameter.

**Comment by ZeiP** [comment]
Ok. I created a PR #2208 for fixing this with the GET parameter.

**Comment by mattr-** [comment]
Fixed by #2208
