### ISSUE TITLE
Improve rack-mini-profiler integration and display

### ISSUE THREAD

**Issue by mattr-** [TracksApp/tracks#2221]
rack-mini-profiler is the tool we use in development that shows up in the upper right hand corner of the page.

Here's a screenshot of the small bits of information it displays:
![image](https://user-images.githubusercontent.com/77174/57586643-431b9480-74be-11e9-830c-ab9f5be17253.png)

When you expand one of those, you get a view like this:
![image](https://user-images.githubusercontent.com/77174/57586649-5f1f3600-74be-11e9-9543-28cdcda01823.png)

While I like the information that rack-mini-profiler displays, I really dislike the way it's integrated on the page. I'd prefer to be able to have a bar across the top of the page that could be toggled on or off, based off the way that [Peek](https://github.com/peek/peek) does it. 

If we can't customize how rack-mini-profiler is displayed, then we can switch to peek.

**Comment by srbaker** [comment]
I'll replace this with Peek. Stay tuned.

**Comment by srbaker** [comment]
I've got a PR to replace this with Peek #2228, but I don't like Peek as much as I like MiniProfiler. So I've also got a PR to move MiniProfiler to the bottom left: #2229.

**Comment by mattr-** [comment]
Closed by #2229
