### ISSUE TITLE
REST API XML missing root element (<head/> then expected element)

### ISSUE THREAD

**Issue by ryannowarm** [TracksApp/tracks#2230]
When I GET any of the top-level XML URLs I get a <head/> element then the expected element(ex: <contexts>).

```
curl -s -u myuser:mypass -H "Content-Type: text/xml" https://example.com/tracks/contexts.xml | head
<?xml version="1.0" encoding="UTF-8"?>
<head/><contexts type="array">
<context>
<id type="integer">9</id>
<name>@Office</name>
<position type="integer">0</position>
<created-at type="dateTime">2015-02-09T15:59:21-06:00</created-at>
<updated-at type="dateTime">2019-05-16T18:57:45-05:00</updated-at>
<state>active</state>
</context>
```

That means that there's really not a root element since there are 2 top-level elements.  This breaks most XML parsers since it violates the XML spec(a single root element is required).

We should get rid of the weird <head/> element so that the expected element(ex: <contexts>) becomes the required root element.

**Comment by ZeiP** [comment]
Which version are you using? I'm not getting the head element with the most recent VCS version:
```
zeip@jameson ~ » curl -s -u myuser:mypass -H "Content-Type: text/xml" https://tracks.example.com/contexts.xml | head 
<?xml version="1.0" encoding="UTF-8"?>
<contexts type="array">
  <context>
```

**Comment by ryannowarm** [comment]
On Fri, May 17, 2019 at 12:02:28AM -0700, Jyri-Petteri Paloposki wrote:
> Which version are you using?
2.3.0

> I'm not getting the head element with the most recent VCS version:
> ```
> zeip@jameson ~ » curl -s -u myuser:mypass -H "Content-Type: text/xml" https://tracks.example.com/contexts.xml | head
> <?xml version="1.0" encoding="UTF-8"?>
> <contexts type="array">
>   <context>
> ```
IMPORTANT NOTICE: The contents of this email and any attachments are confidential and may also be privileged. If you are not the intended recipient, please notify the sender immediately and do not disclose the contents to any other person, use it for any purpose, or store or copy the information in any medium. Thank you.

**Comment by ZeiP** [comment]
@ryannowarm, could you try with the most recent VCS version?

**Comment by ryannowarm** [comment]
@ZeiP, tracks is a pretty mission critical tool for my day-to-day.  At this point I don't have another test environment and I don't feel comfortable moving my production environment forward to HEAD.  This bug is relatively minor for me since I can currently work around it.

**Comment by ZeiP** [comment]
I'm not seeing this in the current VCS version, so I'll close the issue. We're planning the new release in #2218, feel free to open a new issue if the current VCS version or the upcoming release still show this bug.
