### ISSUE TITLE
Adding todo: form not emptied, todo list not updated

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#2242]
I'm on 6ad1e2cf93556a45542421f375178da1531d0e2c. When I create a new todo, it is added without any error, but I only see it after refreshing the page. The create-todo-form still shows the todo data. I expect the new todo to be shown without a reload (it was fading in before?), and I expect the form to be empty/filled with defaults.

**Comment by mattr-** [comment]
Is this while running in dev or running in prod?

**Comment by C-Otto** [comment]
Prod

**Comment by C-Otto** [comment]
Same when deleting a todo

**Comment by C-Otto** [comment]
It works when adding a project, though.

**Comment by ZeiP** [comment]
The bug was caused by #2055, in which the context container's ID logic was changed a bit (from c[ID] to context_[ID]).
