### ISSUE TITLE
Non-Flash statistics are not shown

### ISSUE THREAD

**Issue by C-Otto** [TracksApp/tracks#2246]
I'm on 6ad1e2cf93556a45542421f375178da1531d0e2c. I'm unable to find the comment/issue I already created for this, sorry.

Using both Firefox and Chrome I don't see any graph or picture on the statistics page. In Chrome I see: 

```
stats:194 Uncaught ReferenceError: Chart is not defined
    at initChart (stats:194)
```

**Comment by ZeiP** [comment]
Yep, thanks for opening an issue for this! The comment itself is in #2231.

**Comment by ZeiP** [comment]
I tried setting up a fresh environment, but it seems to work correctly for me. Are you seeing any problems in the console? I'm wondering if loading /assets/Chart.min.js has failed for some reason.

**Comment by C-Otto** [comment]
Oh, I didn't do the assets:precompile step. Sorry, that fixed it...  So pretty!
