### ISSUE TITLE
Task time and notification

### ISSUE THREAD

**Issue by brtsos** [TracksApp/tracks#2265]
Hi, I know it is GTD, but sometime I need set task time (example for meeting). It's cool when I get a notificatin on Android about it.

Great Work!

**Comment by ZeiP** [comment]
IMO this is something you should use a separate calendar software for. There are, however, issues #1461 and #741 which relate to the pretty much same thing.

**Comment by ZeiP** [comment]
Closing this as duplicate of #1461.
