### ISSUE TITLE
No Signups at start.

### ISSUE THREAD

**Issue by Foxtrod89** [TracksApp/tracks#2268]
**You don't have permission to sign up for a new account** at localhost/sighup locataion. How to create new account?
OS- Windows 7
Boxed bundle - Turnkey Virtual Box 15.1
upd: I believe because of this  _# Set to true to allow anyone to sign up for a username.
open_signups: false_

**Comment by mattr-** [comment]
If `open_signups` is `false`, then no one is allowed to sign up. If you change it to `true` and create an account for yourself, then you can change it back to `false` and keep other folks from signing up afterwards.
