### ISSUE TITLE
Constraint mismatch: `todos.description` has max length of 300 in model and 255 in DB.

### ISSUE THREAD

**Issue by whoisutsav** [TracksApp/tracks#2274]
Hi,

Discovered the following issue when analyzing the tracks app as part of a research project. The field `description` in the object `todos` is limited to max length 300 in the model, but 255 in DB. So if a user creates a description greater than 255 but less than 300, it seems they may encounter a problem.

Model validation:
```
class Todo < ApplicationRecord

  MAX_DESCRIPTION_LENGTH = 300
  ...
  validates_presence_of :description
  validates_length_of :description, :maximum => MAX_DESCRIPTION_LENGTH
  ...
```

DB field, which defaults to 255 for string fields in mysql:
```
MariaDB [tracks]> describe todos;
+-------------------+--------------+------+-----+---------+----------------+
| Field             | Type         | Null | Key | Default | Extra          |
+-------------------+--------------+------+-----+---------+----------------+
| id                | bigint(20)   | NO   | PRI | NULL    | auto_increment |
...
| description       | varchar(255) | NO   |     | NULL    |                |
```

I think the best solution may be to limit the length in the model to 255 (and shouldn't create any  conflicts since the field cannot be greater than length 255 in MySQL). Assuming you agree this is an issue, I can create a pull request if that is helpful. Thanks.

**Comment by mattr-** [comment]
Go for it! I'll happily merge that PR. :metal:
