### ISSUE TITLE
Docker Question

### ISSUE THREAD

**Issue by gerroon** [TracksApp/tracks#2304]
Hi

Can you please give me basic example of how to to use the volumes in the docker-compose.yml so  I can deploy it locally here. I am not familiar with the syntax in there atm.

thanks

**Comment by bacizone** [comment]
For 
`docker pull tracksapp/tracks`
I get this:
```
Using default tag: latest
Error response from daemon: manifest for tracksapp/tracks:latest not found: manifest unknown: manifest unknown
```
What is wrong and how to fix?

**Comment by mattr-** [comment]
the `latest` tag doesn't exist on docker hub.

Also, the current docker setup is not meant for production usage, and providing help with how to use and understand docker is not something we're equipped to do.
