### ISSUE TITLE
Request: Tracks as Hipster Composer

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#236]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/236_

I would like Tracks to have a "Hipster PDA" composer function.  Format output for 3x5, vertical in my mind but maybe horizontal.  Print 4 to a page or direct to 3x5.

Projects, one per card.

NextAction lists, one context per card (or if @home is too big, a second card would be fine).

Consider when in NextAction cards it should also put the { Project } it is associated with, appended to the NextAction.

Listing as Design/Apperance because I think the bits are still there, just needs to have a VIEW defined for this.  

_Originally reported by Anonymous on March 3, 2006 at 07:56:06 (-0600)_

**Comment by mattr-** [comment]
Not likely to implement this. Closing.
