### ISSUE TITLE
Assets missing in the production environment

### ISSUE THREAD

**Issue by sccarr** [TracksApp/tracks#2368]
Hi this is what it looks like for me when it boots up.  
<img width="314" alt="Screen Shot 2020-04-04 at 19 55 50" src="https://user-images.githubusercontent.com/26010142/78463739-7fe01380-76ae-11ea-94f6-8b0a3053fd7b.png">
Any ideas what I might have done wrong?  
I did do this
`touch .skip-docker`
to get it to even go past
`bundle exec rails server -e production`
because otherwise it said 
`/Users/me/Desktop/Internal/tracks/bin/../script/docker-environment: line 17: exec: docker-compose: not found`

**Comment by chriscz** [comment]
Try running it in development instead of production and see if it goes away. This looks like an issue with asset discovery. If development environment succeeds then that was definitely the issue.

**Comment by sccarr** [comment]
Yes, running it in development mode fixed the interface.  Looks normal now.  
<img width="1418" alt="screenshot" src="https://user-images.githubusercontent.com/26010142/78851506-edaa7900-79e7-11ea-97f3-3145150e4a6f.png">
I'm still having trouble with the production environment for some reason.  Now when I try to login, it says "login unsuccessful"/"We're sorry, but something went wrong." 
Is there any drawback to me running it in development instead of production all the time? Sorry, I'm new to this

**Comment by chriscz** [comment]
@sccarr If you're running it just for yourself, i.e. not exposing it to the internet it should be OK. 
You might meed to preload the database before you can actually run the application by running a `rake db:schema:load` AFAIR this will wipe any existing data in the database.

**Comment by tet3** [comment]
If you're using the Rails server to serve static files (`serve_static_assets: true` in `site.yml`), it might be [this issue](https://groups.google.com/forum/#!topic/TracksApp/fwvSAlWYkCE) reported on the mailing list. You have to use an environment variable,  `RAILS_SERVE_STATIC_FILES` instead of the yml setting now. So `$export RAILS_SERVE_STATIC_FILES=true` before launching would fix it.
