### ISSUE TITLE
Design new UI colors

### ISSUE THREAD

**Issue by ZeiP** [TracksApp/tracks#2439]
The UI coloring is pretty dated. There are some contrast problems and it's quite heavy. Need to figure out a more modern color palette and take it into use.

**Comment by stderr-enst** [comment]
I like the idea and your screenshots made me realize that the header and the box on the side are not even the same color?

Would it be possible to make the primary-/secondary colors an option in the preferences? Personally I prefer the grey/dark version.

**Comment by ZeiP** [comment]
It's quite a bit more difficult to have them freely selectable by the user – also because I think there are actually quite many colors that need to be selected to make sure they're compatible with the primary and secondary colors (enough contrast etc.)  A more realistic direction would probably be having a few different options and of course the freedom to create your own version if you make your own stylesheet for your own installation.

Do you mean the current version by the ”grey/dark” version? As suggested in the PR (I think) it would probably make sense to also have a version with dark background for evening/night time use, but that's different from the current version.

**Comment by stderr-enst** [comment]
Ah, if that is the case then it makes sense to provide something like two options.

I was referring to the current version, yes. Although, it would make sense to have the box on the side in the same color as the header in the current version as well.

A version with a dark background would also be nice, but I don't know if I would use it. It always depends I guess. :)
