### ISSUE TITLE
Security Vulnerability Discovered 

### ISSUE THREAD

**Issue by jthorpe6** [TracksApp/tracks#2464]
Hi 
I found a vulnerability in TRACKS version 2.4.2. Are you happy for me to disclose it here or is there another means to inform you about the vulnerability ?

**Comment by ZeiP** [comment]
@jthorpe6, just wanted to confirm that the necessary information regarding sending security issues encrypted is available in the security documentation: https://github.com/TracksApp/tracks/blob/master/SECURITY.md  I also replied to your email, but pinging just in case the reply went to the spam folder or something.
