### ISSUE TITLE
Recurring todo UI is broken on master

### ISSUE THREAD

**Issue by GregSutcliffe** [TracksApp/tracks#2468]
Fresh install of Tracks, master as of two days ago, built using "docker build". When I go to create a recurring todo, this is what I see:

![image](https://user-images.githubusercontent.com/827786/91825518-4c40ef80-ec34-11ea-8c99-3b44e4dc58e3.png)

This happens on Firefox 79, Chromium 84, and mobile (Android) Firefox. I don't see any errors in the browser console.

Happy to test out fixes, etc, if anyone has a thought on what's happening.

**Comment by ZeiP** [comment]
The same thing (un)fortunately also happens on my installation, I'll try to fix it ASAP. Sorry for not noticing this, my bad!

**Comment by ZeiP** [comment]
@GregSutcliffe, I figured out a (non-optimal) way to fix this. Not sure why it broke, but at least for me it's now fixed. Let me know if you encounter any more problems with this or something else. I'll make a new release soon, but I have a few other things on my mind before that.

**Comment by GregSutcliffe** [comment]
Thanks for the fast fix @ZeiP! I'll build a new Docker image shortly and try it out - I'll report back after that.

**Comment by GregSutcliffe** [comment]
Seems to be working, thanks again! There's a really minor issue with the tag search too, but I'll open a new issue for that :)
