### ISSUE TITLE
Publish #tracks on Matrix

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#2486]
https://matrix.org/ and https://element.io/ provide an easy-to-join-but-also-Open mechanism to access #tracks on Freenode, which Gitter doesn't quite manage to equal.

This already works, but it would be a good bit smoother if the Matrix servers had OP in the channel and if the #freenode_#tracks:matrix.org room were officially published on Matrix as #tracks.

This documentation on how to do that may be accurate (though note that it is for KDE's self-hosted Matrix server at kde.org rather than the shared one at matrix.org): https://community.kde.org/Matrix#How_to_Add_Your_Existing_IRC_Channel_as_Room

See https://prometheus.io/community/ (and actually go check out the channel and notice how you see all the history) for a great example of this use.

I think it would then be worth recommending this for chat access and dropping Gitter.

**Comment by ZeiP** [comment]
Great idea, thanks! Gitter is pretty much used by no-one, so I agree we should use something else instead – #tracks has had at least some activity recently. I'll take a look into this.
