### ISSUE TITLE
Starred list is empty.

### ISSUE THREAD

**Issue by wfouche** [TracksApp/tracks#2527]
https://app.taskitin.fi/ using Tracks 2.5.1, does not display any tasks which are starred when selected the "Starred" menu option.

**Comment by ZeiP** [comment]
You're right, I'll take a look at it – thanks!

**Comment by ZeiP** [comment]
@wfouche, thanks for the report! The bug fix is now deployed in Taskitin. The GitHub CI line seems to be a bit messed up for some reason. I'll try to merge the fix to the source control ASAP as well and will close the issue down once I get that done.

**Comment by wfouche** [comment]
That is amazing. I did not even have to log out. Working just perfectly fine now. Thanks!
