### ISSUE TITLE
Error when changing the due date of a task from the Calendar view.

### ISSUE THREAD

**Issue by wfouche** [TracksApp/tracks#2534]
https://app.taskitin.fi/ using Tracks 2.5.1, display error "There was an error retrieving from server: error" whenever the due date of a task in the Calendar view is changed and saved. From Projects or Contexts, the due date can be changed and saved successfully.

**Comment by ZeiP** [comment]
Thanks for the report! It seems that changing the due date in the calendar view does indeed fail with an error in certain cases, but not always. I'll try to fix this ASAP.

**Comment by ZeiP** [comment]
Seems that I made the breaking change in abad8c77e when fixing #2472. I created a PR for the fix, but it's still pending for automatic tests being created for this and fixing the GitHub CI pipeline. I, however, deployed the fix to Taskitin app already, so this should be fixed there.

**Comment by wfouche** [comment]
Thanks! It is working now.
