### ISSUE TITLE
next actions with sensitive due-date doesn't automatically sorted with Ajax

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#256]
*Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/256*

When I add new next action with due date set it goes to the bottom of the specified context unconditionally.

It's only gets sorted to a proper place of the list when I refresh the page.

*Originally reported by Anonymous on April 4, 2006 at 21:01:30 (+0800)*

**Comment by C-Otto** [comment]
I'm working on this, and have a working prototype. My approach is to add a `datasort="..."` attribute to each action's `div`. The value is the unix epoch derived fromt he actions `due` attribute. The sorting is done using JavaScript, although I still need to figure out where to put the code (adding actions and sorting is happening in many places, it seems).

Is this a feasible approach?
