### ISSUE TITLE
Wrong localization in Date pickers

### ISSUE THREAD

**Issue by ymitsos** [TracksApp/tracks#2603]
Hi,

After a recent upgrade to 2.5.2, I am facing an issue with the two date drop-downs menus; namely the "Due" and "Shown from". The language used in the months and date fields is not correct.

I am running a non-docker version in one FreeBSD box. The command `sudo -u www bundle exec rake time:zones:local` returns correctly my timezone and the related cities under this locale but for some reason the selected language in the javascript menus is wrong.

The issue relates only to the locales of the 2 drop-downs. No to the rest of the UI.

**Comment by ZeiP** [comment]
Thanks for the report! Do you mean the Javascript date picker's language? The date picker being always in Russian is a known issue #2553; if it's something else, could you attach a screenshot?

**Comment by ymitsos** [comment]
oh, you are absolutely right @ZeiP, my bad I din't search so thoroughly the list with open issues. Indeed the workaround worked for me. Thank you very much!
