### ISSUE TITLE
Delegate Tasks and/or Projects to other users.

### ISSUE THREAD

**Issue by thsobota** [TracksApp/tracks#2618]
Tracks is Great!  Thank you.  I started using Tracks and one benefit is the simplicity. I can understand the reluctance to add more features so that it does not get bloated.  The multi-user functionality is good.  I am using this to help me run my small business with 6 people.  It would be useful to have a mechanism to easily delegate Tasks or whole Projects to other employees. This would be particularly useful as we expect to have a "hybrid" work model where employees will continue to work from remote sites.

**Comment by ZeiP** [comment]
There's a previous issue for this in #527, so I'm closing this as a duplicate. I agree this would be very useful, but unfortunately don't currently have the time to implement such a feature – however, I'd be happy to review and help with any PR:s if you or someone else can contribute to this.
