### ISSUE TITLE
Change layout for Edit Action box

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#265]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/265_

I use the Edit Action box a lot to keep a running update of the task status, email snippets, etc.  There are a few simple changes that would make it a bit more useful:
1. Increase the text box size (maybe even configurable)
2. Have a button that would pop-up a much larger standalone text box in its own browser window (like some of the blog 'Add a comment' features do)
3. Add Submit and Cancel to the top of the window since often times they're off the bottom of the screen.

I changed the view template for my own installation to deal with 1 and 3 and I like it better, though something like this may be highly user dependent.

Regards,
Jim

_Originally reported by Anonymous on April 4, 2006 at 06:33:47 (-0400)_

**Comment by C-Otto** [comment]
I think this issue can be closed. The text field can be increased by dragging the lower right corner (in recent browsers at least?) and I don't see an issue with the buttons' positions. Besides, the popup can be closed by pressing Enter (in certain input fields).
