### ISSUE TITLE
Mimemagic out of date in Gemfile

### ISSUE THREAD

**Issue by GregSutcliffe** [TracksApp/tracks#2654]
Doing a new install via Docker Compose, I get this for the web container:

> Your bundle is locked to mimemagic (0.3.5) from rubygems repository
https://rubygems.org/ or installed locally, but that version can no longer be
found in that source. That means the author of mimemagic (0.3.5) has removed it.
You'll need to update your bundle to a version other than mimemagic (0.3.5) that
hasn't been removed in order to install.

Sure enough, it has - https://rubygems.org/gems/mimemagic/versions has 0.3.7 as the lowest version.

I tried added `RUN bundle update mimemagic` to the Dockerfile but sadly it bombed out with a bundler exception. Is there another way to update it?

**Comment by ZeiP** [comment]
@GregSutcliffe, which version are you using? Unfortunately there hasn't been a release in a while (I'm actually just about to make a new one, just one small issue to fix before it), so currently the best bet is using the code in the master branch, which should have mimemagic as version 0.3.10.

**Comment by GregSutcliffe** [comment]
@ZeiP good catch - yes I'm on 2.5.1. I switched to master and the compose finished.

However, I can't start it:

```
[root@cobalt]# ./script/server                                                                                             /opt/tracks:master
WARNING: The RAILS_ENV variable is not set. Defaulting to a blank string.
WARNING: The DATABASE_NAME variable is not set. Defaulting to a blank string.
Starting tracks_db_1 ... done
rake aborted!
OptionParser::AmbiguousOption: ambiguous option: -b
/app/bin/run-rake:5:in `<main>'

Caused by:
OptionParser::InvalidOption: invalid option: b
Did you mean?  B
/app/bin/run-rake:5:in `<main>'
(See full trace by running task with --trace)
```

Thoughts?

**Comment by ZeiP** [comment]
This is likely caused by the new non-Ruby scripts created to fix #2442. Thanks for reporting, I'll try to figure out what's going wrong there.

**Comment by GregSutcliffe** [comment]
Thanks, that's got it. Out of interest, is there a reason why compose doesn't use the prebuilt container mentioned in the pure Docker instructions?

**Comment by ZeiP** [comment]
I haven't thought about it, I think the Compose file was done by @mattr-. I suppose the idea is to run the exact version you want and to be able to test changes too, if you're a developer. We could of course have a plain compose file that would be able to run Tracks without making a clone of the codebase :thinking:

**Comment by GregSutcliffe** [comment]
Makes sense. I went with compose because I was trying to shortcut the various setup steps in the plain Docker setup, rather than run a devel version of Tracks :)

I'll see about setting up a plain compose file, I can send a PR if I get it working fine.

**Comment by ZeiP** [comment]
Sounds good!
