### ISSUE TITLE
Most recent docker image doesn't seem to run (shows rails new usage)

### ISSUE THREAD

**Issue by lyonzy** [TracksApp/tracks#2688]
The most recent docker image pushed in the last few days for some reason doesn't run for me - it's showing the usage of `rails new` then exiting. It seems to be the same symptom these folks are experiencing:
https://stackoverflow.com/questions/17645041/why-doesnt-rails-s-work-from-the-app-directory
https://stackoverflow.com/questions/38909344/why-does-the-rails-command-force-a-help-message-for-the-new-command

It sounds like it's something wrong with what's in `bin/` but I'm not enough of a rails expert to know what. I've found that there are two workarounds:
 - run `rake app:update:bin` before `rails server -b 0.0.0.0` (couldn't get this to agree with docker-compose though)
 - (less invasive) change the cmd to `bin/rails server -b 0.0.0.0`

Although I assume these are just workarounds and there might be something needed in the Dockerfile? I couldn't see anything in yesterday's git history that would be an obvious cause but I wonder if it's related to the rails version bumps.

**Comment by ZeiP** [comment]
Thanks for the report! I'll check it out. Running the same image did seem to work for me, but it may be that I've missed something.

**Comment by yuroller** [comment]
Updated just now and I have the same kind of error:

```
admin@Blackbox2:~$ sudo docker logs 68d7d854b654
Usage:
  rails new APP_PATH [options]

Options:
      [--skip-namespace], [--no-skip-namespace]              # Skip namespace (affects only isolated applications)
  -r, [--ruby=PATH]                                          # Path to the Ruby binary of your choice
                                                             # Default: /usr/local/bin/ruby
  -m, [--template=TEMPLATE]                                  # Path to some application template (can be a filesystem path or URL)
  -d, [--database=DATABASE]                                  # Preconfigure for selected database (options: mysql/postgresql/sqlite3/oracle/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                                             # Default: sqlite3
      [--skip-gemfile], [--no-skip-gemfile]                  # Don't create a Gemfile
  -G, [--skip-git], [--no-skip-git]                          # Skip .gitignore file
      [--skip-keeps], [--no-skip-keeps]                      # Skip source control .keep files
  -M, [--skip-action-mailer], [--no-skip-action-mailer]      # Skip Action Mailer files
      [--skip-action-mailbox], [--no-skip-action-mailbox]    # Skip Action Mailbox gem
      [--skip-action-text], [--no-skip-action-text]          # Skip Action Text gem
  -O, [--skip-active-record], [--no-skip-active-record]      # Skip Active Record files
...```

Do you have any procedure on how to fix?
Thanks

**Comment by ZeiP** [comment]
There indeed seemed to be some kind of a weird error relating to the rails server command. I'm a bit baffled why it didn't happen in my other environments, but I think it's now fixed in master, though I'm having a bit of trouble reproducing the fix in my test system. Can you please try pulling the latest master image (docker pull tracksapp/tracks:master) and then running that?

**Comment by yuroller** [comment]
I did not try the new docker image, but I manually changed the command inside the container json in /var/lib/docker/containers/../config.json/ to read "bin/rails" instead of "rails", then restarted the daemon and it worked.

**Comment by ZeiP** [comment]
Yeah, that's the same fix, so it's probably ok now. Sorry for the inconvenience, unfortunate that it didn't show up in either my own tests or in the CI pipeline. Still a bit baffled by why that is :thinking:
