### ISSUE TITLE
Changing the language in Preferences UI crashes the installation

### ISSUE THREAD

**Issue by aghybris** [TracksApp/tracks#2690]
Changing the language in Preferences UI crashes the installation:
I changed the language to "de"

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

I am unsing a fresh image on proxmox
debian-10-turnkey-tracks_16.1-1_amd64.tar.gz   2021-11-29 22:03:23

Could not find anything in the logs.

**Comment by ZeiP** [comment]
For that error message there should be something in the Rails error log. Unfortunately I'm not familiar with proxmox so I don't really know how you can find the log... Switching to the de language works for me ok. Are you experiencing issues with any other functionalities? Are other locales (for example fi) working for you?

**Comment by ZeiP** [comment]
Closing due to there being a month without response, maybe the problem solved itself. Feel free to comment if you're still experiencing the problem.

**Comment by castillocon** [comment]
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Changing the language in Preferences , error ??

**Comment by castillocon** [comment]
TurnkeyLinux Tracks

**Comment by friki67** [comment]
Hello! Same thing here. Can you please tell me where to look for the pertinent log?
