### ISSUE TITLE
`poll-for-db` script hangs indefinitely

### ISSUE THREAD

**Issue by notlesh** [TracksApp/tracks#2703]
The `poll-for-db` script will hang on the curl invocation `curl -sf telnet://db:3306 >/dev/null && exit` indefinitely. This causes the calling `script/setup.sh` script to hang, which seemingly prevents the database initialization from occurring.

Reference: https://github.com/TracksApp/tracks/blob/17e0bae77d26b71ac64eb1dfd67030cf769d3e4f/script/poll-for-db#L7

I was able to work around this by replacing the loop with a timeout on the order of 30 seconds and then calling `exit`.

**Comment by ZeiP** [comment]
The idea of the script is to only continue after the database is up and responsive. Did you try running the curl command yourself; is the DB responding properly?

**Comment by notlesh** [comment]
> The idea of the script is to only continue after the database is up and responsive. Did you try running the curl command yourself; is the DB responding properly?

I did, it hangs indefinitely when run manually. I didn't dig in much more than that, but I'm happy to. I'd suggest an alternative, but I'm not much of a docker expert :)

**Comment by ZeiP** [comment]
Ah, right. That's actually quite interesting, I think it's meant to bail out in a while if the connection's unavailable and then try again for 60 times.

I think it might make sense to explicitely define a timeout for the command. Could you try using the following command instead?
`curl -sf -m 10 telnet://db:3306 >/dev/null && exit`

**Comment by ZeiP** [comment]
The script had some issues that were fixed in #2726. The issues mainly appeared if the DB connection wasn't working anyway, but as this has now considerably changed I'll close the issue. If you have any further problems, feel free to comment and ask to re-open or open a new issue.
