### ISSUE TITLE
Uploads dir doesn't exist

### ISSUE THREAD

**Issue by jaaacck** [TracksApp/tracks#2730]
Currently the uploads path doesn't exist and throws this error when trying to import a backup:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/7045733/153012913-68d7e357-a148-4439-9c51-f089a421e6b7.png">

To get this to work I had to create the folder manually under /public/uploads/csv.
I am using the docker method mentioned here: https://github.com/TracksApp/tracks/blob/master/doc/installation.md#docker-installation-using-docker-compose

**Comment by ZeiP** [comment]
Ah, interesting. I probably haven't tested the importer for a while, this is likely a bug. I'll take a look soon.
