### ISSUE TITLE
Current docker image cannot start

### ISSUE THREAD

**Issue by blacktav** [TracksApp/tracks#2738]
Seems to be the entrypoint for rails failing: logs rails usage comments

**Comment by ZeiP** [comment]
Thanks for the report. Can you please provide a copy-paste showing both the commands you've ran and the output? Did you follow the instructions in https://github.com/TracksApp/tracks/blob/master/doc/installation.md?

**Comment by blacktav** [comment]
I pulled & ran the docker image on hub.docker; that failed

So I followed the "Docker installation using a separate container" since I already have a populated database (I am migrating physical servers at the moment) and build an image

1. downloaded the 2.5.2 zip file and unpacked it
2. docker build -t="tracks" . (creating an image)
3. and then a complicated "run" command with these switches
```
Network      : --net asgard-25-net --ip 172.25.0.5
 Name         : tracks
 Restart rule : --restart unless-stopped
 Volumes      :  -v /var/lib/docker-containers/asgard/tracks/mnt/:/mnt/ -v /var/log/docker-containers/asgard/tracks/log:/log
 Envars       :  -e DATABASE_NAME=tracks -e DATABASE_HOST=172.25.0.1 -e DATABASE_PORT=5432 -e DATABASE_USERNAME=frodo -e DATABASE_PASSWORD=bilbo -e DATABASE_TYPE=postgresql -e DATABASE_ENCODING=unicode -e RAILS_ENV=production
 Hostvar      : -h asgard-tracks
 Logging cfg  :  --log-opt max-size=10m --log-opt max-file=3
 ID           : 8ed114b21223
```
The database is fine as it being accessed from other ruby systems without issue

The container just spins unable to come up, no bash available.
docker logs tracks just reports the rails usage page

I tried to create a brand new instance with no database defined but same behaviour

**Comment by blacktav** [comment]
Oh building the image did report some issues; I am running it again to get the output

**Comment by blacktav** [comment]
There is a message at line 408
```
Step 15/18 : RUN RAILS_ENV=production bundle exec rake assets:precompile
 ---> Running in 8a76aa5a8626
ESC[91mfatal: not a git repository (or any of the parent directories): .git
```
[logger.txt](https://github.com/TracksApp/tracks/files/8104589/logger.txt)

**Comment by ZeiP** [comment]
Ah. That error is actually likely not the problem, it seems to be somewhat normal.

Could you try using the most recent code (master branch)?

**Comment by blacktav** [comment]
OK, working on it

**Comment by blacktav** [comment]
Yep, that worked a treat - no issues at all
Site now reports v2.5.3

Nice one :)

**Comment by ZeiP** [comment]
Great :)  I've been meaning to do a release any time now, I think there's about one issue I'd like to solve before that. Hopefully soon.

**Comment by ngophuong** [comment]
> Hey, just to confirm new docker image tracksapp/tracks work great
> 
> 
> 
> Thanks for all your help & efforts; super project

Hi there, good day to you. I am also interested in the apps. could you help share your docker-compose.yml file for the configuration to start the tracks apps from official docket image ?

**Comment by ZeiP** [comment]
@ngophuong, there's currently no docker-compose image for running with the Docker Hub version, though that might indeed be useful. The current instructions are available in https://github.com/TracksApp/tracks/blob/master/doc/installation.md . If you have problems with installation, please open a new issue or pop up at our IRC channel #tracks@libera.

**Comment by ngophuong** [comment]
Thank you for quick feedback. I managed to completed the installation. Really enjoy the software so far 👍🏻

**Comment by Shahin-rmz** [comment]
Hello, I am interested and thrilled to use tracks.
As far as I see the Project uses Maria DB as database.
Is there known issues for having the project on Rasoberry pi?
Is project compatible with ARM 64 CPU?
thanks

**Comment by ZeiP** [comment]
Technically there aren't any known issues running Tracks on a Raspberry PI – it's running on Ruby and MariaDB (or Postgres, or SQLite), so architecture shouldn't matter all that much. The recommended way of running it Docker, however, and I'm not sure if Docker is an optimal technology to use on Raspberry PI, so it might require some additional work to get it running without Docker, if necessary.

**Comment by Shahin-rmz** [comment]
@ZeiP thanks for reply.
I'm running/self hosting around 9 Services on Raspberry pi.
So literally it won't be a problem.
Thanks.
