### ISSUE TITLE
Does taskitin.fi support email integrations?

### ISSUE THREAD

**Issue by sam-be** [TracksApp/tracks#2743]
I registered on taskitin.fi to support this project, but it's not clear if there's email integrations enabled. I understand this would need to be configured on the server/instance.

Apologies if this isn't the right place, but perhaps the maintainer could confirm? 
Thanks

**Comment by ZeiP** [comment]
I've been meaning to take a look at it, so now there is! In Taskitin it goes a bit differently:

1. Open your Preferences and go to the Tracks behaviour tab.
2. Choose an email address of the format something@app.taskitin.fi and enter it to the From email field.
3. Enter all email addresses you want to send tasks from to the Permitted email senders 
4. Send the actions via email to the email address you chose in phase 2.

Let me know if you have any problems with it!
