### ISSUE TITLE
add duration estimation for activity

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#276]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/276_

It would be nice to supplement task description with esimation of duration (say, in minutes) required for this task to be completed.

It would help in deciding what task could be taken for work at the moment and to estimate what effort need to be done to accomplish context or project (in addition to # of tasks displayed at the very top of the page).

Small 3-digit box near task description in "Add a next action" menu would be enough.

One more related feature is to allow fixation of elapsed time (in similar 3-digit box near task description in context or home page).

That would facilitate in creation of activity reports (how did I spend a day). They are not timesheets in any case but may help to understand in what task(s) I invested (wasted) so much time also serving as a source for time management improvement.

_Originally reported by Anonymous on May 5, 2006 at 03:53:08 (+0530)_

**Comment by mattr-** [comment]
Closing this in favor of #2022
