### ISSUE TITLE
Changing the language in Preferences , error ??

### ISSUE THREAD

**Issue by castillocon** [TracksApp/tracks#2792]
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Changing the language in Preferences , error ??

Using https://www.turnkeylinux.org/tracks

**Comment by ZeiP** [comment]
I think this issue has been fixed in v2.5.2 while Turnkey is still providing 2.5.1. Upgrading the Turnkey image to 2.6.0 should fix the issue.
