### ISSUE TITLE
Postgres command is wrong in 'Docker installation using separate container'

### ISSUE THREAD

**Issue by john2exonets** [TracksApp/tracks#2845]
In the Installation doc (https://github.com/TracksApp/tracks/blob/master/doc/installation.md ) the Postgres command to create the 'tracks' user for the database has the wrong syntax -- it doesn't have all the roles needed for tracks to work!

In the Docs:

   `postgres=# CREATE USER tracks WITH ENCRYPTED PASSWORD 'password-goes-here';`

What it needs to be in order for tracks to work with the database:

`postgres=# CREATE ROLE tracks WITH LOGIN NOSUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION PASSWORD 'password-goes-here';`

Your database setup command will die with an "Unable to drop database" error when you run the 'bin/rake db:reset' if you don't give the user the CREATEDB role.  You can use the `ENCRYPTED PASSWORD` option, but it needs to be in SCRAM-SHA-256 format to be accepted.

**Comment by ZeiP** [comment]
Fixed, thanks!
