### ISSUE TITLE
Automatic refresh

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#295]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/295_

I'd love to see the ability to set a META HTTP-EQUIV=REFRESH value on the main page. It's necessary, in my opinion, now that we have an API that allows users to add new tasks via interfaces other than the web page itself. For instance, if I add a few new things via a Quicksilver command, and then later return to my main Tracks page, which has been sitting in the background somewhere, those new items won't be visible until I refresh the page. As a result, I sometimes forget that such items are there for quite a while. But if the page refreshed itself automatically at some pre-set interval, such items would eventually show back up.

I see this as being implemented by a new preference. By default, the refresh would be set to '0,' which would mean not to include a refresh tag on the main page. A user could enter a numeric value equal to the number of minutes between refreshes. (When implementing the tag, this numeric value would have to be multiplied by 60, as the refresh tag counts in seconds rather than minutes.)

_Originally reported by Anonymous on May 5, 2006 at 23:19:53 (+0800)_

**Comment by mattr-** [comment]
If it's not already done (which it could be, based on the existing comments), I don't intend on implementing this.
