### ISSUE TITLE
Display multiple contexts in a single list

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#309]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/309_

I'd like to see the ability to select multiple contexts in a single list.  I never seem to get to my "@calls" actions because they're way below the "work" and "computer" contexts on my home page.

What I'd like to see instead would be a way to select the contexts I can work on now and have them show the actions from all of those contexts in a single list.  The current sorting (and any future enhancements to it) would cause my older actions to filter to the top when I can work on them.

Combined with the feature requested in ticket:48 it would allow you to do some really neat things that are discussed in the book.  You could create time and effort contexts for example.  Then you could sit down at the computer at work between meetings for example and select @Work or @Computer actions that should only take @Time - 15m and see them all in the same list.

Perhaps the next day I'm working from home.  I could select @Work - Computer and @Home since I can get a few things done around the house.  Maybe its been a long week so I only want to select things that are @Easy.

_Originally reported by Anonymous on June 6, 2006 at 07:59:26 (+0200)_

**Comment by C-Otto** [comment]
Related to #1193?

**Comment by mattr-** [comment]
Closing in favor of #1193
