### ISSUE TITLE
Enable synchronization with mobile devices/other systems

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#452]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/452_

It would be nice to be able to synchronize my tracks data with my PocketPC or mobile phone. To make it possible there are a couple of simple things that could be done:    
- add a "date/time of last update" field to todos, projects, contexts, ... tables,  and make sure this field is updated every time a record is changed or created.  
- update the API so that it would be possible to get all records modified since a given date and to update a record with new information (but never allow the id field to be changed).

These steps leave out the deleted records which is a bit harder. To be able to track that it would be needed to have a table of deleted ids (and, again, date/time of deletion) and some API methods to get deleted records since a given date and to delete a record giving it's id.

These changes would be sufficient to enable synchronization between platforms and would enable the development of "sometimes connected" applications to enable taking our todos with us.

_Originally reported by Anonymous on February 2, 2007 at 10:47:07 (+0000)_

**Comment by mattr-** [comment]
Won't fix. With the proliferation of Wifi and decent phone service in most places, this need for this is greatly reduced.
