### ISSUE TITLE
bookmarklet to create action including "link:"current url

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#507]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/507_

It would be nice to be able to create a new action from a bookmarklet putting the current URL in the note field, and perhaps using "read "+the title of the current page as the action name. Ideally would select the read/review context by default.

I'm thinking this would be better than #107 just because it would be really integrated, as opposed to just a sidebar. The whole point of GTD is that you only look at one thing, right? :)

Anyway, thanks for the awesome tool!

_Originally reported by Anonymous on April 4, 2007 at 02:52:51 (+0100)_

**Comment by mattr-** [comment]
I'm not eager to support adding a bookmarklet. Closing.
