### ISSUE TITLE
Context drop-down should appear too if there is always an context

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#668]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/668_

At Tracks 1.5rc1 i have to clear the context field befor i get the drop down. This is really bad if i what to change the context. 

I suggest to open the context drop down ever when the user clicks to the context field and not changed the text.

_Originally reported by Anonymous on March 3, 2008 at 23:00:06 (+0200)_

**Comment by C-Otto** [comment]
I don't understand this issue, could you explain? Is it still relevant?
