### ISSUE TITLE
Notes & Notebooks

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#783]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/783_

For me, notes are nearly 50% of my work flow and all work there after comes from those notes.  Lets beef up tracks and make it more complete by adding the concept of notes books that contain notes, list, etc rather than just "one ofs" that are hand cuffed to a project.

One should be able to create a notebook on a business subject and then throughout any project entry or action, reference that.  

Maybe a smart way to do that would be that you can create sections in a note book, then, in a project note or action you can easily reference that somehow in a way that when viewing that project note you could click on the reference and it would expand that section in whatever notebook.

Example:

"So this is an example of a note in a project.  The requirements for this project are X, Y, B.  B is a very complicated, core business methodology that can be referenced here (here would be a enhanced link). Blah blah blah"

So one would then click on here, and either a dialog friendly box would then come up that would allow you to see the reference material and project note.

Just some thoughts that would greatly improve my usage of tracks.

_Originally reported by Anonymous on October 10, 2008 at 17:07:23 (-0500)_

**Comment by mattr-** [comment]
I intend to convert from Textile to Markdown for notes with 3.0, but I don't really intend on adding Notebooks.
