### ISSUE TITLE
Number of actions contains completed actions. Should be configurable

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#788]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/788_

Hi!

I have several hidden contexts. In sidebar a number of actions within that context is displayed.

However I find it very misleading to have (9 actions) near a context and after clicking it "Currently there are no incomplete actions in this context"...

I always think that I have something to be done but is not so. Can it be made configurable if actions count contain uncompleted, completed and total number of actions?

_Originally reported by Anonymous on October 10, 2008 at 15:34:14 (+0100)_

**Comment by C-Otto** [comment]
This seems to be fixed?

**Comment by mattr-** [comment]
Old bug. Likely fixed. Closing
