### ISSUE TITLE
Patch Adds Sortable and Dragable Todo Items

### ISSUE THREAD

**Issue by dnrce** [TracksApp/tracks#937]
_Migrated from the original issue at https://www.assembla.com/spaces/tracks-tickets/tickets/937_

Added the ability to sort to do items in either a context list or a project list to set a sequence.  Or, you can drag an item to other contexts on the same page (on home page.)

This does "break" the current sort by due date" view - but I really wanted to be able to put my items in sequence that makes sense to me.

Looks like this is related to open "someday/maybe" tickets 
- "Reorder Next Actions" (#91)
- "Drag and Drop Between Contexts" (#220 )

Hope this is something others can use.  Probably need to provide a way to sort by due date before incorporating into the main stream..so people that rely on that can still do it.

It doesn't look like too much more work to drag items into the "completed" container to mark them as complete (or out, if you change your mind), and dragging to defer makes a lot of sense, to visually sort what you will do tomorrow vs. today..But I'll leave that for someday/maybe :-)

_Originally reported by tom_v on September 9, 2009 at 21:21:22 (-0400)_

**Comment by mattr-** [comment]
While still a useful feature, this request is so out of date, i'm just going to close it rather than leave it open.
